Octree iterator class
#include <pcl/octree/octree_iterator.h>
Public Member Functions
OctreeFixedDepthIterator ()
Empty constructor.
OctreeFixedDepthIterator (OctreeT *octree_arg, uindex_t fixed_depth_arg=0)
Constructor.
OctreeFixedDepthIterator (OctreeT *octree_arg, uindex_t fixed_depth_arg, IteratorState *current_state, const std::deque< IteratorState > &fifo=std::deque< IteratorState >())
Constructor.
OctreeFixedDepthIterator (const OctreeFixedDepthIterator &other)
Copy Constructor.
OctreeFixedDepthIterator & operator= (const OctreeFixedDepthIterator &src)
Copy assignment.
void reset (uindex_t fixed_depth_arg)
Reset the iterator to the first node at the depth given as parameter.
void reset ()
Reset the iterator to the first node at the current depth.
Public Member Functions inherited from pcl::octree::OctreeBreadthFirstIterator< OctreeT >
OctreeBreadthFirstIterator (uindex_t max_depth_arg=0)
Empty constructor.
OctreeBreadthFirstIterator (OctreeT *octree_arg, uindex_t max_depth_arg=0)
Constructor.
OctreeBreadthFirstIterator (OctreeT *octree_arg, uindex_t max_depth_arg, IteratorState *current_state, const std::deque< IteratorState > &fifo=std::deque< IteratorState >())
Constructor.
OctreeBreadthFirstIterator (const OctreeBreadthFirstIterator &other)
Copy Constructor.
OctreeBreadthFirstIterator & operator= (const OctreeBreadthFirstIterator &src)
Copy operator.
void reset ()
Reset the iterator to the root node of the octree.
OctreeBreadthFirstIterator & operator++ ()
Preincrement operator.
OctreeBreadthFirstIterator operator++ (int)
postincrement operator.
Public Member Functions inherited from pcl::octree::OctreeIteratorBase< OctreeT >
OctreeIteratorBase ()
Empty constructor.
OctreeIteratorBase (uindex_t max_depth_arg)
Constructor.
OctreeIteratorBase (OctreeT *octree_arg)
Constructor.
OctreeIteratorBase (OctreeT *octree_arg, uindex_t max_depth_arg)
Constructor.
OctreeIteratorBase (OctreeT *octree_arg, uindex_t max_depth_arg, IteratorState *current_state)
Constructor.
virtual ~OctreeIteratorBase ()=default
Empty deconstructor.
bool operator== (const OctreeIteratorBase &other) const
Equal comparison operator.
bool operator!= (const OctreeIteratorBase &other) const
Inequal comparison operator.
void reset ()
Reset iterator.
const OctreeKey & getCurrentOctreeKey () const
Get octree key for the current iterator octree node.
uindex_t getCurrentOctreeDepth () const
Get the current depth level of octree.
OctreeNode * getCurrentOctreeNode () const
Get the current octree node.
bool isBranchNode () const
check if current node is a branch node
bool isLeafNode () const
check if current node is a branch node
virtual OctreeNode * operator* () const
*operator.
char getNodeConfiguration () const
Get bit pattern of children configuration of current node.
const LeafContainer & getLeafContainer () const
Method for retrieving a single leaf container from the octree leaf node.
LeafContainer & getLeafContainer ()
Method for retrieving a single leaf container from the octree leaf node.
const BranchContainer & getBranchContainer () const
Method for retrieving the container from an octree branch node.
BranchContainer & getBranchContainer ()
Method for retrieving the container from an octree branch node.
virtual unsigned long getNodeID () const
get a integer identifier for current node (note: identifier depends on tree depth).
Protected Attributes
uindex_t fixed_depth_
Given level of the node to be iterated.
Protected Attributes inherited from pcl::octree::OctreeBreadthFirstIterator< OctreeT >
std::deque< IteratorState > FIFO_
FIFO list.
Protected Attributes inherited from pcl::octree::OctreeIteratorBase< OctreeT >
OctreeT * octree_
Reference to octree class.
IteratorState * current_state_
Pointer to current iterator state.
uindex_t max_octree_depth_
Maximum octree depth.
Additional Inherited Members
Public Types inherited from pcl::octree::OctreeBreadthFirstIterator< OctreeT >
using BranchNode = typename OctreeIteratorBase< OctreeT >::BranchNode
using LeafNode = typename OctreeIteratorBase< OctreeT >::LeafNode
Public Types inherited from pcl::octree::OctreeIteratorBase< OctreeT >
using iterator_category = std::forward_iterator_tag
using value_type = const OctreeNode
using difference_type = void
using pointer = const OctreeNode *
using reference = const OctreeNode &
using LeafNode = typename OctreeT::LeafNode
using BranchNode = typename OctreeT::BranchNode
using LeafContainer = typename OctreeT::LeafContainer
using BranchContainer = typename OctreeT::BranchContainer
Detailed Description
template<typename OctreeT>
class pcl::octree::OctreeFixedDepthIterator< OctreeT >
Octree iterator class
Note
Iterator over all existing nodes at a given depth. It walks across an octree in a breadth-first manner.
Author
Fabien Rozar (fabie.nosp@m.n.ro.nosp@m.zar@g.nosp@m.mail.nosp@m..com)
Definition at line 581 of file octree_iterator.h.
Constructor & Destructor Documentation
OctreeFixedDepthIterator() [1/4]
template<typename OctreeT > pcl::octree::OctreeFixedDepthIterator< OctreeT >::OctreeFixedDepthIterator
Empty constructor.
Definition at line 260 of file octree_iterator.hpp.
OctreeFixedDepthIterator() [2/4]
template<typename OctreeT > pcl::octree::OctreeFixedDepthIterator< OctreeT >::OctreeFixedDepthIterator (OctreeT * octree_arg, uindex_t fixed_depth_arg = 0) explicit
Constructor.
Parameters
[in] octree_arg Octree to be iterated. Initially the iterator is set to its root node.
[in] fixed_depth_arg Depth level during traversal
Definition at line 266 of file octree_iterator.hpp.
References pcl::octree::OctreeFixedDepthIterator< OctreeT >::reset().
OctreeFixedDepthIterator() [3/4]
template<typename OctreeT > pcl::octree::OctreeFixedDepthIterator< OctreeT >::OctreeFixedDepthIterator (OctreeT * octree_arg, uindex_t fixed_depth_arg, IteratorState * current_state, const std::deque< IteratorState > & fifo = std::deque<IteratorState>()) inline
Constructor.
Parameters
[in] octree_arg Octree to be iterated. Initially the iterator is set to its root node.
[in] fixed_depth_arg Depth level during traversal
[in] current_state A pointer to the current iterator state
[in] fifo Internal container of octree node to go through
Warning
For advanced users only.
Definition at line 607 of file octree_iterator.h.
OctreeFixedDepthIterator() [4/4]
template<typename OctreeT > pcl::octree::OctreeFixedDepthIterator< OctreeT >::OctreeFixedDepthIterator (const OctreeFixedDepthIterator< OctreeT > & other) inline
Copy Constructor.
Parameters
[in] other Another OctreeFixedDepthIterator to copy from
Definition at line 620 of file octree_iterator.h.
References pcl::octree::OctreeFixedDepthIterator< OctreeT >::fixed_depth_.
Member Function Documentation
operator=()
template<typename OctreeT > OctreeFixedDepthIterator& pcl::octree::OctreeFixedDepthIterator< OctreeT >::operator= (const OctreeFixedDepthIterator< OctreeT > & src) inline
Copy assignment.
Parameters
[in] src the iterator to copy into this
Returns
pointer to the current octree node
Definition at line 631 of file octree_iterator.h.
References pcl::octree::OctreeFixedDepthIterator< OctreeT >::fixed_depth_, and pcl::octree::OctreeBreadthFirstIterator< OctreeT >::operator=().
reset() [1/2]
template<typename OctreeT > void pcl::octree::OctreeFixedDepthIterator< OctreeT >::reset () inline
Reset the iterator to the first node at the current depth.
Definition at line 648 of file octree_iterator.h.
References pcl::octree::OctreeFixedDepthIterator< OctreeT >::fixed_depth_.
Referenced by pcl::octree::OctreeFixedDepthIterator< OctreeT >::OctreeFixedDepthIterator().
reset() [2/2]
template<typename OctreeT > void pcl::octree::OctreeFixedDepthIterator< OctreeT >::reset (uindex_t fixed_depth_arg)
Reset the iterator to the first node at the depth given as parameter.
Parameters
[in] fixed_depth_arg Depth level during traversal
Definition at line 277 of file octree_iterator.hpp.
References pcl::octree::OctreeBreadthFirstIterator< OctreeT >::operator++(), and pcl::octree::OctreeBreadthFirstIterator< OctreeT >::reset().
Member Data Documentation
fixed_depth_
template<typename OctreeT > uindex_t pcl::octree::OctreeFixedDepthIterator< OctreeT >::fixed_depth_ protected
Given level of the node to be iterated.
Definition at line 657 of file octree_iterator.h.
Referenced by pcl::octree::OctreeFixedDepthIterator< OctreeT >::OctreeFixedDepthIterator(), pcl::octree::OctreeFixedDepthIterator< OctreeT >::operator=(), and pcl::octree::OctreeFixedDepthIterator< OctreeT >::reset().
The documentation for this class was generated from the following files:
pcl/octree/octree_iterator.h
pcl/octree/impl/octree_iterator.hpp
© 20092012, Willow Garage, Inc.
© 2012, Open Perception, Inc.
Licensed under the BSD License.
https://pointclouds.org/documentation/classpcl_1_1octree_1_1_octree_fixed_depth_iterator.html