ExtractIndices extracts a set of indices from a point cloud.
#include <pcl/filters/extract_indices.h>
Public Types
using Ptr = shared_ptr< ExtractIndices< PointT > >
using ConstPtr = shared_ptr< const ExtractIndices< PointT > >
Public Types inherited from pcl::FilterIndices< PointT >
using PointCloud = pcl::PointCloud< PointT >
using Ptr = shared_ptr< FilterIndices< PointT > >
using ConstPtr = shared_ptr< const FilterIndices< PointT > >
Public Types inherited from pcl::Filter< PointT >
using Ptr = shared_ptr< Filter< PointT > >
using ConstPtr = shared_ptr< const Filter< PointT > >
using PointCloud = pcl::PointCloud< PointT >
using PointCloudPtr = typename PointCloud::Ptr
using PointCloudConstPtr = typename PointCloud::ConstPtr
Public Types inherited from pcl::PCLBase< PointT >
using PointCloud = pcl::PointCloud< PointT >
using PointCloudPtr = typename PointCloud::Ptr
using PointCloudConstPtr = typename PointCloud::ConstPtr
using PointIndicesPtr = PointIndices::Ptr
using PointIndicesConstPtr = PointIndices::ConstPtr
Public Member Functions
ExtractIndices (bool extract_removed_indices=false)
Constructor.
void filterDirectly (PointCloudPtr &cloud)
Apply the filter and store the results directly in the input cloud.
Public Member Functions inherited from pcl::FilterIndices< PointT >
FilterIndices (bool extract_removed_indices=false)
Constructor.
void filter (Indices &indices)
Calls the filtering method and returns the filtered point cloud indices.
void setNegative (bool negative)
Set whether the regular conditions for points filtering should apply, or the inverted conditions.
bool getNegative () const
Get whether the regular conditions for points filtering should apply, or the inverted conditions.
void setKeepOrganized (bool keep_organized)
Set whether the filtered points should be kept and set to the value given through setUserFilterValue (default: NaN), or removed from the PointCloud, thus potentially breaking its organized structure.
bool getKeepOrganized () const
Get whether the filtered points should be kept and set to the value given through setUserFilterValue (default = NaN), or removed from the PointCloud, thus potentially breaking its organized structure.
void setUserFilterValue (float value)
Provide a value that the filtered points should be set to instead of removing them.
Public Member Functions inherited from pcl::Filter< PointT >
Filter (bool extract_removed_indices=false)
Empty constructor.
IndicesConstPtr const getRemovedIndices () const
Get the point indices being removed.
void getRemovedIndices (PointIndices &pi)
Get the point indices being removed.
void filter (PointCloud &output)
Calls the filtering method and returns the filtered dataset in output.
Public Member Functions inherited from pcl::PCLBase< PointT >
PCLBase ()
Empty constructor.
PCLBase (const PCLBase &base)
Copy constructor.
virtual ~PCLBase ()=default
Destructor.
virtual void setInputCloud (const PointCloudConstPtr &cloud)
Provide a pointer to the input dataset.
PointCloudConstPtr const getInputCloud () const
Get a pointer to the input point cloud dataset.
virtual void setIndices (const IndicesPtr &indices)
Provide a pointer to the vector of indices that represents the input data.
virtual void setIndices (const IndicesConstPtr &indices)
Provide a pointer to the vector of indices that represents the input data.
virtual void setIndices (const PointIndicesConstPtr &indices)
Provide a pointer to the vector of indices that represents the input data.
virtual void setIndices (std::size_t row_start, std::size_t col_start, std::size_t nb_rows, std::size_t nb_cols)
Set the indices for the points laying within an interest region of the point cloud.
IndicesPtr getIndices ()
Get a pointer to the vector of indices used.
IndicesConstPtr const getIndices () const
Get a pointer to the vector of indices used.
const PointT & operator[] (std::size_t pos) const
Override PointCloud operator[] to shorten code.
Protected Types
using PointCloud = typename FilterIndices< PointT >::PointCloud
using PointCloudPtr = typename PointCloud::Ptr
using PointCloudConstPtr = typename PointCloud::ConstPtr
using FieldList = typename pcl::traits::fieldList< PointT >::type
Protected Member Functions
void applyFilter (PointCloud &output) override
Filtered results are stored in a separate point cloud.
void applyFilter (Indices &indices) override
Filtered results are indexed by an indices array.
void applyFilterIndices (Indices &indices)
Filtered results are indexed by an indices array.
Protected Member Functions inherited from pcl::FilterIndices< PointT >
void applyFilter (PointCloud &output) override
Abstract filter method for point cloud.
Protected Member Functions inherited from pcl::Filter< PointT >
const std::string & getClassName () const
Get a string representation of the name of this class.
Protected Member Functions inherited from pcl::PCLBase< PointT >
bool initCompute ()
This method should get called before starting the actual computation.
bool deinitCompute ()
This method should get called after finishing the actual computation.
Additional Inherited Members
Protected Attributes inherited from pcl::FilterIndices< PointT >
bool negative_
False = normal filter behavior (default), true = inverted behavior.
bool keep_organized_
False = remove points (default), true = redefine points, keep structure.
float user_filter_value_
The user given value that the filtered point dimensions should be set to (default = NaN).
Protected Attributes inherited from pcl::Filter< PointT >
IndicesPtr removed_indices_
Indices of the points that are removed.
std::string filter_name_
The filter name.
bool extract_removed_indices_
Set to true if we want to return the indices of the removed points.
Protected Attributes inherited from pcl::PCLBase< PointT >
PointCloudConstPtr input_
The input point cloud dataset.
IndicesPtr indices_
A pointer to the vector of point indices to use.
bool use_indices_
Set to true if point indices are used.
bool fake_indices_
If no set of indices are given, we construct a set of fake indices that mimic the input PointCloud.
Detailed Description
template<typename PointT>
class pcl::ExtractIndices< PointT >
ExtractIndices extracts a set of indices from a point cloud.
Usage example:
pcl::ExtractIndices<PointType> eifilter (true); // Initializing with true will allow us to extract the removed indices
eifilter.setInputCloud (cloud_in);
eifilter.setIndices (indices_in);
eifilter.filter (*cloud_out);
// The resulting cloud_out contains all points of cloud_in that are indexed by indices_in
indices_rem = eifilter.getRemovedIndices ();
// The indices_rem array indexes all points of cloud_in that are not indexed by indices_in
eifilter.setNegative (true);
eifilter.filter (*indices_out);
// Alternatively: the indices_out array is identical to indices_rem
eifilter.setNegative (false);
eifilter.setUserFilterValue (1337.0);
eifilter.filterDirectly (cloud_in);
// This will directly modify cloud_in instead of creating a copy of the cloud
// It will overwrite all fields of the filtered points by the user value: 1337
pcl::ExtractIndicesExtractIndices extracts a set of indices from a point cloud.Definition: extract_indices.h:70
pcl::ExtractIndices
ExtractIndices extracts a set of indices from a point cloud.
Definition: extract_indices.h:70
Author
Radu Bogdan Rusu
Definition at line 69 of file extract_indices.h.
Member Typedef Documentation
ConstPtr
template<typename PointT > using pcl::ExtractIndices< PointT >::ConstPtr = shared_ptr<const ExtractIndices<PointT> >
Definition at line 80 of file extract_indices.h.
FieldList
template<typename PointT > using pcl::ExtractIndices< PointT >::FieldList = typename pcl::traits::fieldList<PointT>::type protected
Definition at line 75 of file extract_indices.h.
PointCloud
template<typename PointT > using pcl::ExtractIndices< PointT >::PointCloud = typename FilterIndices<PointT>::PointCloud protected
Definition at line 72 of file extract_indices.h.
PointCloudConstPtr
template<typename PointT > using pcl::ExtractIndices< PointT >::PointCloudConstPtr = typename PointCloud::ConstPtr protected
Definition at line 74 of file extract_indices.h.
PointCloudPtr
template<typename PointT > using pcl::ExtractIndices< PointT >::PointCloudPtr = typename PointCloud::Ptr protected
Definition at line 73 of file extract_indices.h.
Ptr
template<typename PointT > using pcl::ExtractIndices< PointT >::Ptr = shared_ptr<ExtractIndices<PointT> >
Definition at line 79 of file extract_indices.h.
Constructor & Destructor Documentation
ExtractIndices()
template<typename PointT > pcl::ExtractIndices< PointT >::ExtractIndices (bool extract_removed_indices = false) inline
Constructor.
Parameters
[in] extract_removed_indices Set to true if you want to be able to extract the indices of points being removed (default = false).
Definition at line 85 of file extract_indices.h.
References pcl::Filter< PointT >::filter_name_, and pcl::PCLBase< PointT >::use_indices_.
Member Function Documentation
applyFilter() [1/2]
template<typename PointT > void pcl::ExtractIndices< PointT >::applyFilter (Indices & indices) inline override protected virtual
Filtered results are indexed by an indices array.
Parameters
[out] indices The resultant indices.
Implements pcl::FilterIndices< PointT >.
Definition at line 125 of file extract_indices.h.
References pcl::ExtractIndices< PointT >::applyFilterIndices().
applyFilter() [2/2]
template<typename PointT > void pcl::ExtractIndices< PointT >::applyFilter (PointCloud & output) override protected virtual
Filtered results are stored in a separate point cloud.
Parameters
[out] output The resultant point cloud.
Implements pcl::Filter< PointT >.
Definition at line 79 of file extract_indices.hpp.
References pcl::copyPointCloud(), and pcl::PointCloud< PointT >::is_dense.
applyFilterIndices()
template<typename PointT > void pcl::ExtractIndices< PointT >::applyFilterIndices (Indices & indices) protected
Filtered results are indexed by an indices array.
Parameters
[out] indices The resultant indices.
Definition at line 118 of file extract_indices.hpp.
Referenced by pcl::ExtractIndices< PointT >::applyFilter().
filterDirectly()
template<typename PointT > void pcl::ExtractIndices< PointT >::filterDirectly (PointCloudPtr & cloud)
Apply the filter and store the results directly in the input cloud.
This method will save the time and memory copy of an output cloud but can not alter the original size of the input cloud: It operates as though setKeepOrganized() is true and will overwrite the filtered points instead of remove them. All fields of filtered points are replaced with the value set by setUserFilterValue() (default = NaN). This method also automatically alters the input cloud set via setInputCloud(). It does not alter the value of the internal keep organized boolean as set by setKeepOrganized().
Parameters
cloud The point cloud used for input and output.
Definition at line 48 of file extract_indices.hpp.
The documentation for this class was generated from the following files:
pcl/filters/extract_indices.h
pcl/filters/impl/extract_indices.hpp
© 20092012, Willow Garage, Inc.
© 2012, Open Perception, Inc.
Licensed under the BSD License.
https://pointclouds.org/documentation/classpcl_1_1_extract_indices.html