#include <pcl/features/feature.h>
Public Types
using PointCloudN = pcl::PointCloud< PointNT >
using PointCloudNPtr = typename PointCloudN::Ptr
using PointCloudNConstPtr = typename PointCloudN::ConstPtr
using Ptr = shared_ptr< FeatureFromNormals< PointInT, PointNT, PointOutT > >
using ConstPtr = shared_ptr< const FeatureFromNormals< PointInT, PointNT, PointOutT > >
Public Types inherited from pcl::Feature< PointInT, PointOutT >
using BaseClass = PCLBase< PointInT >
using Ptr = shared_ptr< Feature< PointInT, PointOutT > >
using ConstPtr = shared_ptr< const Feature< PointInT, PointOutT > >
using KdTree = pcl::search::Search< PointInT >
using KdTreePtr = typename KdTree::Ptr
using PointCloudIn = pcl::PointCloud< PointInT >
using PointCloudInPtr = typename PointCloudIn::Ptr
using PointCloudInConstPtr = typename PointCloudIn::ConstPtr
using PointCloudOut = pcl::PointCloud< PointOutT >
using SearchMethod = std::function< int(std::size_t, double, pcl::Indices &, std::vector< float > &)>
using SearchMethodSurface = std::function< int(const PointCloudIn &cloud, std::size_t index, double, pcl::Indices &, std::vector< float > &)>
Public Types inherited from pcl::PCLBase< PointInT >
using PointCloud = pcl::PointCloud< PointInT >
using PointCloudPtr = typename PointCloud::Ptr
using PointCloudConstPtr = typename PointCloud::ConstPtr
using PointIndicesPtr = PointIndices::Ptr
using PointIndicesConstPtr = PointIndices::ConstPtr
Public Member Functions
FeatureFromNormals ()
Empty constructor.
void setInputNormals (const PointCloudNConstPtr &normals)
Provide a pointer to the input dataset that contains the point normals of the XYZ dataset.
PointCloudNConstPtr getInputNormals () const
Get a pointer to the normals of the input XYZ point cloud dataset.
Public Member Functions inherited from pcl::Feature< PointInT, PointOutT >
Feature ()
Empty constructor.
void setSearchSurface (const PointCloudInConstPtr &cloud)
Provide a pointer to a dataset to add additional information to estimate the features for every point in the input dataset.
PointCloudInConstPtr getSearchSurface () const
Get a pointer to the surface point cloud dataset.
void setSearchMethod (const KdTreePtr &tree)
Provide a pointer to the search object.
KdTreePtr getSearchMethod () const
Get a pointer to the search method used.
double getSearchParameter () const
Get the internal search parameter.
void setKSearch (int k)
Set the number of k nearest neighbors to use for the feature estimation.
int getKSearch () const
get the number of k nearest neighbors used for the feature estimation.
void setRadiusSearch (double radius)
Set the sphere radius that is to be used for determining the nearest neighbors used for the feature estimation.
double getRadiusSearch () const
Get the sphere radius used for determining the neighbors.
void compute (PointCloudOut &output)
Base method for feature estimation for all points given in <setInputCloud (), setIndices ()> using the surface in setSearchSurface () and the spatial locator in setSearchMethod ()
Public Member Functions inherited from pcl::PCLBase< PointInT >
PCLBase ()
Empty constructor.
PCLBase (const PCLBase &base)
Copy constructor.
virtual ~PCLBase ()=default
Destructor.
virtual void setInputCloud (const PointCloudConstPtr &cloud)
Provide a pointer to the input dataset.
PointCloudConstPtr const getInputCloud () const
Get a pointer to the input point cloud dataset.
virtual void setIndices (const IndicesPtr &indices)
Provide a pointer to the vector of indices that represents the input data.
virtual void setIndices (const IndicesConstPtr &indices)
Provide a pointer to the vector of indices that represents the input data.
virtual void setIndices (const PointIndicesConstPtr &indices)
Provide a pointer to the vector of indices that represents the input data.
virtual void setIndices (std::size_t row_start, std::size_t col_start, std::size_t nb_rows, std::size_t nb_cols)
Set the indices for the points laying within an interest region of the point cloud.
IndicesPtr getIndices ()
Get a pointer to the vector of indices used.
IndicesConstPtr const getIndices () const
Get a pointer to the vector of indices used.
const PointInT & operator[] (std::size_t pos) const
Override PointCloud operator[] to shorten code.
Protected Member Functions
virtual bool initCompute ()
This method should get called before starting the actual computation.
Protected Member Functions inherited from pcl::Feature< PointInT, PointOutT >
const std::string & getClassName () const
Get a string representation of the name of this class.
virtual bool deinitCompute ()
This method should get called after ending the actual computation.
int searchForNeighbors (std::size_t index, double parameter, pcl::Indices &indices, std::vector< float > &distances) const
Search for k-nearest neighbors using the spatial locator from setSearchmethod, and the given surface from setSearchSurface.
int searchForNeighbors (const PointCloudIn &cloud, std::size_t index, double parameter, pcl::Indices &indices, std::vector< float > &distances) const
Search for k-nearest neighbors using the spatial locator from setSearchmethod, and the given surface from setSearchSurface.
Protected Member Functions inherited from pcl::PCLBase< PointInT >
bool initCompute ()
This method should get called before starting the actual computation.
bool deinitCompute ()
This method should get called after finishing the actual computation.
Protected Attributes
PointCloudNConstPtr normals_
A pointer to the input dataset that contains the point normals of the XYZ dataset.
Protected Attributes inherited from pcl::Feature< PointInT, PointOutT >
std::string feature_name_
The feature name.
SearchMethodSurface search_method_surface_
The search method template for points.
PointCloudInConstPtr surface_
An input point cloud describing the surface that is to be used for nearest neighbors estimation.
KdTreePtr tree_
A pointer to the spatial search object.
double search_parameter_
The actual search parameter (from either search_radius_ or k_).
double search_radius_
The nearest neighbors search radius for each point.
int k_
The number of K nearest neighbors to use for each point.
bool fake_surface_
If no surface is given, we use the input PointCloud as the surface.
Protected Attributes inherited from pcl::PCLBase< PointInT >
PointCloudConstPtr input_
The input point cloud dataset.
IndicesPtr indices_
A pointer to the vector of point indices to use.
bool use_indices_
Set to true if point indices are used.
bool fake_indices_
If no set of indices are given, we construct a set of fake indices that mimic the input PointCloud.
Detailed Description
template<typename PointInT, typename PointNT, typename PointOutT>
class pcl::FeatureFromNormals< PointInT, PointNT, PointOutT >
Definition at line 308 of file feature.h.
Member Typedef Documentation
ConstPtr
template<typename PointInT , typename PointNT , typename PointOutT > using pcl::FeatureFromNormals< PointInT, PointNT, PointOutT >::ConstPtr = shared_ptr< const FeatureFromNormals<PointInT, PointNT, PointOutT> >
Definition at line 321 of file feature.h.
PointCloudN
template<typename PointInT , typename PointNT , typename PointOutT > using pcl::FeatureFromNormals< PointInT, PointNT, PointOutT >::PointCloudN = pcl::PointCloud<PointNT>
Definition at line 316 of file feature.h.
PointCloudNConstPtr
template<typename PointInT , typename PointNT , typename PointOutT > using pcl::FeatureFromNormals< PointInT, PointNT, PointOutT >::PointCloudNConstPtr = typename PointCloudN::ConstPtr
Definition at line 318 of file feature.h.
PointCloudNPtr
template<typename PointInT , typename PointNT , typename PointOutT > using pcl::FeatureFromNormals< PointInT, PointNT, PointOutT >::PointCloudNPtr = typename PointCloudN::Ptr
Definition at line 317 of file feature.h.
Ptr
template<typename PointInT , typename PointNT , typename PointOutT > using pcl::FeatureFromNormals< PointInT, PointNT, PointOutT >::Ptr = shared_ptr< FeatureFromNormals<PointInT, PointNT, PointOutT> >
Definition at line 320 of file feature.h.
Constructor & Destructor Documentation
FeatureFromNormals()
template<typename PointInT , typename PointNT , typename PointOutT > pcl::FeatureFromNormals< PointInT, PointNT, PointOutT >::FeatureFromNormals () inline
Empty constructor.
Definition at line 329 of file feature.h.
Member Function Documentation
getInputNormals()
template<typename PointInT , typename PointNT , typename PointOutT > PointCloudNConstPtr pcl::FeatureFromNormals< PointInT, PointNT, PointOutT >::getInputNormals () const inline
Get a pointer to the normals of the input XYZ point cloud dataset.
Definition at line 343 of file feature.h.
References pcl::FeatureFromNormals< PointInT, PointNT, PointOutT >::normals_.
initCompute()
template<typename PointInT , typename PointNT , typename PointOutT > bool pcl::FeatureFromNormals< PointInT, PointNT, PointOutT >::initCompute protected virtual
This method should get called before starting the actual computation.
Reimplemented from pcl::Feature< PointInT, PointOutT >.
Reimplemented in pcl::VFHEstimation< PointInT, PointNT, PointOutT >, pcl::SHOTColorEstimationOMP< PointInT, PointNT, PointOutT, PointRFT >, pcl::SHOTEstimationOMP< PointInT, PointNT, PointOutT, PointRFT >, pcl::SHOTEstimationBase< PointInT, PointNT, PointOutT, PointRFT >, pcl::SHOTEstimationBase< PointInT, PointNT, pcl::SHOT352, pcl::ReferenceFrame >, pcl::SHOTEstimationBase< PointInT, PointNT, pcl::SHOT1344, pcl::ReferenceFrame >, pcl::FLARELocalReferenceFrameEstimation< PointInT, PointNT, PointOutT, SignedDistanceT >, and pcl::ShapeContext3DEstimation< PointInT, PointNT, PointOutT >.
Definition at line 232 of file feature.hpp.
References pcl::Feature< PointInT, PointOutT >::deinitCompute().
setInputNormals()
template<typename PointInT , typename PointNT , typename PointOutT > void pcl::FeatureFromNormals< PointInT, PointNT, PointOutT >::setInputNormals (const PointCloudNConstPtr & normals) inline
Provide a pointer to the input dataset that contains the point normals of the XYZ dataset.
In case of search surface is set to be different from the input cloud, normals should correspond to the search surface, not the input cloud!
Parameters
[in] normals the const boost shared pointer to a PointCloud of normals. By convention, L2 norm of each normal should be 1.
Definition at line 339 of file feature.h.
References pcl::FeatureFromNormals< PointInT, PointNT, PointOutT >::normals_.
Referenced by pcl::GRSDEstimation< PointInT, PointNT, PointOutT >::computeFeature(), pcl::UnaryClassifier< PointT >::computeFPFH(), pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::computeRf(), pcl::HarrisKeypoint6D< PointInT, PointOutT, NormalT >::detectKeypoints(), and pcl::ism::ImplicitShapeModelEstimation< FeatureSize, PointT, NormalT >::estimateFeatures().
Member Data Documentation
normals_
template<typename PointInT , typename PointNT , typename PointOutT > PointCloudNConstPtr pcl::FeatureFromNormals< PointInT, PointNT, PointOutT >::normals_ protected
A pointer to the input dataset that contains the point normals of the XYZ dataset.
Definition at line 349 of file feature.h.
Referenced by pcl::FeatureFromNormals< PointInT, PointNT, PointOutT >::getInputNormals(), and pcl::FeatureFromNormals< PointInT, PointNT, PointOutT >::setInputNormals().
The documentation for this class was generated from the following files:
pcl/features/feature.h
pcl/features/impl/feature.hpp
© 20092012, Willow Garage, Inc.
© 2012, Open Perception, Inc.
Licensed under the BSD License.
https://pointclouds.org/documentation/classpcl_1_1_feature_from_normals.html