CorrespondenceEstimationNormalShooting computes correspondences as points in the target cloud which have minimum distance to normals computed on the input cloud
#include <pcl/registration/correspondence_estimation_normal_shooting.h>
Public Types
using Ptr = shared_ptr< CorrespondenceEstimationNormalShooting< PointSource, PointTarget, NormalT, Scalar > >
using ConstPtr = shared_ptr< const CorrespondenceEstimationNormalShooting< PointSource, PointTarget, NormalT, Scalar > >
using KdTree = pcl::search::KdTree< PointTarget >
using KdTreePtr = typename KdTree::Ptr
using PointCloudSource = pcl::PointCloud< PointSource >
using PointCloudSourcePtr = typename PointCloudSource::Ptr
using PointCloudSourceConstPtr = typename PointCloudSource::ConstPtr
using PointCloudTarget = pcl::PointCloud< PointTarget >
using PointCloudTargetPtr = typename PointCloudTarget::Ptr
using PointCloudTargetConstPtr = typename PointCloudTarget::ConstPtr
using PointCloudNormals = pcl::PointCloud< NormalT >
using NormalsPtr = typename PointCloudNormals::Ptr
using NormalsConstPtr = typename PointCloudNormals::ConstPtr
Public Types inherited from pcl::registration::CorrespondenceEstimationBase< PointSource, PointTarget, float >
using Ptr = shared_ptr< CorrespondenceEstimationBase< PointSource, PointTarget, float > >
using ConstPtr = shared_ptr< const CorrespondenceEstimationBase< PointSource, PointTarget, float > >
using KdTree = pcl::search::KdTree< PointTarget >
using KdTreePtr = typename KdTree::Ptr
using KdTreeReciprocal = pcl::search::KdTree< PointSource >
using KdTreeReciprocalPtr = typename KdTree::Ptr
using PointCloudSource = pcl::PointCloud< PointSource >
using PointCloudSourcePtr = typename PointCloudSource::Ptr
using PointCloudSourceConstPtr = typename PointCloudSource::ConstPtr
using PointCloudTarget = pcl::PointCloud< PointTarget >
using PointCloudTargetPtr = typename PointCloudTarget::Ptr
using PointCloudTargetConstPtr = typename PointCloudTarget::ConstPtr
using PointRepresentationConstPtr = typename KdTree::PointRepresentationConstPtr
Public Types inherited from pcl::PCLBase< PointSource >
using PointCloud = pcl::PointCloud< PointSource >
using PointCloudPtr = typename PointCloud::Ptr
using PointCloudConstPtr = typename PointCloud::ConstPtr
using PointIndicesPtr = PointIndices::Ptr
using PointIndicesConstPtr = PointIndices::ConstPtr
Public Member Functions
CorrespondenceEstimationNormalShooting ()
Empty constructor.
~CorrespondenceEstimationNormalShooting () override=default
Empty destructor.
void setSourceNormals (const NormalsConstPtr &normals)
Set the normals computed on the source point cloud.
NormalsConstPtr getSourceNormals () const
Get the normals of the source point cloud.
bool requiresSourceNormals () const override
See if this rejector requires source normals.
void setSourceNormals (pcl::PCLPointCloud2::ConstPtr cloud2) override
Blob method for setting the source normals.
void determineCorrespondences (pcl::Correspondences &correspondences, double max_distance=std::numeric_limits< double >::max()) override
Determine the correspondences between input and target cloud.
void determineReciprocalCorrespondences (pcl::Correspondences &correspondences, double max_distance=std::numeric_limits< double >::max()) override
Determine the reciprocal correspondences between input and target cloud.
void setKSearch (unsigned int k)
Set the number of nearest neighbours to be considered in the target point cloud.
unsigned int getKSearch () const
Get the number of nearest neighbours considered in the target point cloud for computing correspondences.
CorrespondenceEstimationBase< PointSource, PointTarget, Scalar >::Ptr clone () const override
Clone and cast to CorrespondenceEstimationBase.
Public Member Functions inherited from pcl::registration::CorrespondenceEstimationBase< PointSource, PointTarget, float >
CorrespondenceEstimationBase ()
Empty constructor.
~CorrespondenceEstimationBase () override=default
Empty destructor.
void setInputSource (const PointCloudSourceConstPtr &cloud)
Provide a pointer to the input source (e.g., the point cloud that we want to align to the target)
PointCloudSourceConstPtr const getInputSource ()
Get a pointer to the input point cloud dataset target.
void setInputTarget (const PointCloudTargetConstPtr &cloud)
Provide a pointer to the input target (e.g., the point cloud that we want to align the input source to)
PointCloudTargetConstPtr const getInputTarget ()
Get a pointer to the input point cloud dataset target.
virtual bool requiresTargetNormals () const
See if this rejector requires target normals.
virtual void setTargetNormals (pcl::PCLPointCloud2::ConstPtr)
Abstract method for setting the target normals.
void setIndicesSource (const IndicesPtr &indices)
Provide a pointer to the vector of indices that represent the input source point cloud.
IndicesPtr const getIndicesSource ()
Get a pointer to the vector of indices used for the source dataset.
void setIndicesTarget (const IndicesPtr &indices)
Provide a pointer to the vector of indices that represent the input target point cloud.
IndicesPtr const getIndicesTarget ()
Get a pointer to the vector of indices used for the target dataset.
void setSearchMethodTarget (const KdTreePtr &tree, bool force_no_recompute=false)
Provide a pointer to the search object used to find correspondences in the target cloud.
KdTreePtr getSearchMethodTarget () const
Get a pointer to the search method used to find correspondences in the target cloud.
void setSearchMethodSource (const KdTreeReciprocalPtr &tree, bool force_no_recompute=false)
Provide a pointer to the search object used to find correspondences in the source cloud (usually used by reciprocal correspondence finding).
KdTreeReciprocalPtr getSearchMethodSource () const
Get a pointer to the search method used to find correspondences in the source cloud.
void setPointRepresentation (const PointRepresentationConstPtr &point_representation)
Provide a boost shared pointer to the PointRepresentation to be used when searching for nearest neighbors.
Public Member Functions inherited from pcl::PCLBase< PointSource >
PCLBase ()
Empty constructor.
PCLBase (const PCLBase &base)
Copy constructor.
virtual ~PCLBase ()=default
Destructor.
virtual void setInputCloud (const PointCloudConstPtr &cloud)
Provide a pointer to the input dataset.
PointCloudConstPtr const getInputCloud () const
Get a pointer to the input point cloud dataset.
virtual void setIndices (const IndicesPtr &indices)
Provide a pointer to the vector of indices that represents the input data.
virtual void setIndices (const IndicesConstPtr &indices)
Provide a pointer to the vector of indices that represents the input data.
virtual void setIndices (const PointIndicesConstPtr &indices)
Provide a pointer to the vector of indices that represents the input data.
virtual void setIndices (std::size_t row_start, std::size_t col_start, std::size_t nb_rows, std::size_t nb_cols)
Set the indices for the points laying within an interest region of the point cloud.
IndicesPtr getIndices ()
Get a pointer to the vector of indices used.
IndicesConstPtr const getIndices () const
Get a pointer to the vector of indices used.
const PointSource & operator[] (std::size_t pos) const
Override PointCloud operator[] to shorten code.
Protected Member Functions
bool initCompute ()
Internal computation initialization.
Protected Member Functions inherited from pcl::registration::CorrespondenceEstimationBase< PointSource, PointTarget, float >
const std::string & getClassName () const
Abstract class get name method.
bool initCompute ()
Internal computation initialization.
bool initComputeReciprocal ()
Internal computation initialization for reciprocal correspondences.
Protected Member Functions inherited from pcl::PCLBase< PointSource >
bool initCompute ()
This method should get called before starting the actual computation.
bool deinitCompute ()
This method should get called after finishing the actual computation.
Additional Inherited Members
Protected Attributes inherited from pcl::registration::CorrespondenceEstimationBase< PointSource, PointTarget, float >
std::string corr_name_
The correspondence estimation method name.
KdTreePtr tree_
A pointer to the spatial search object used for the target dataset.
KdTreeReciprocalPtr tree_reciprocal_
A pointer to the spatial search object used for the source dataset.
PointCloudTargetConstPtr target_
The input point cloud dataset target.
IndicesPtr target_indices_
The target point cloud dataset indices.
PointRepresentationConstPtr point_representation_
The point representation used (internal).
PointCloudTargetPtr input_transformed_
The transformed input source point cloud dataset.
std::vector< pcl::PCLPointField > input_fields_
The types of input point fields available.
bool target_cloud_updated_
Variable that stores whether we have a new target cloud, meaning we need to pre-process it again.
bool source_cloud_updated_
Variable that stores whether we have a new source cloud, meaning we need to pre-process it again.
bool force_no_recompute_
A flag which, if set, means the tree operating on the target cloud will never be recomputed.
bool force_no_recompute_reciprocal_
A flag which, if set, means the tree operating on the source cloud will never be recomputed.
Protected Attributes inherited from pcl::PCLBase< PointSource >
PointCloudConstPtr input_
The input point cloud dataset.
IndicesPtr indices_
A pointer to the vector of point indices to use.
bool use_indices_
Set to true if point indices are used.
bool fake_indices_
If no set of indices are given, we construct a set of fake indices that mimic the input PointCloud.
Detailed Description
template<typename PointSource, typename PointTarget, typename NormalT, typename Scalar = float>
class pcl::registration::CorrespondenceEstimationNormalShooting< PointSource, PointTarget, NormalT, Scalar >
CorrespondenceEstimationNormalShooting computes correspondences as points in the target cloud which have minimum distance to normals computed on the input cloud
Code example:
pcl::PointCloud<pcl::PointNormal>::Ptr source, target;
// ... read or fill in source and target
pcl::CorrespondenceEstimationNormalShooting
 <pcl::PointNormal, pcl::PointNormal, pcl::PointNormal> est;
est.setInputSource (source);
est.setSourceNormals (source);
est.setInputTarget (target);
// Test the first 10 correspondences for each point in source, and return the best
est.setKSearch (10);
pcl::Correspondences all_correspondences;
// Determine all correspondences
est.determineCorrespondences (all_correspondences);
pcl::PointCloud::Ptrshared_ptr< PointCloud< PointT > > PtrDefinition: point_cloud.h:413
pcl::PointCloud::Ptr
shared_ptr< PointCloud< PointT > > Ptr
Definition: point_cloud.h:413
pcl::Correspondencesstd::vector< pcl::Correspondence, Eigen::aligned_allocator< pcl::Correspondence > > CorrespondencesDefinition: correspondence.h:89
pcl::Correspondences
std::vector< pcl::Correspondence, Eigen::aligned_allocator< pcl::Correspondence > > Correspondences
Definition: correspondence.h:89
pcl::PointNormalA point structure representing Euclidean xyz coordinates, together with normal coordinates and the su...Definition: point_types.hpp:877
pcl::PointNormal
A point structure representing Euclidean xyz coordinates, together with normal coordinates and the su...
Definition: point_types.hpp:877
Author
Aravindhan K. Krishnan, Radu B. Rusu
Definition at line 79 of file correspondence_estimation_normal_shooting.h.
Member Typedef Documentation
ConstPtr
template<typename PointSource , typename PointTarget , typename NormalT , typename Scalar = float> using pcl::registration::CorrespondenceEstimationNormalShooting< PointSource, PointTarget, NormalT, Scalar >::ConstPtr = shared_ptr<const CorrespondenceEstimationNormalShooting<PointSource, PointTarget, NormalT, Scalar> >
Definition at line 86 of file correspondence_estimation_normal_shooting.h.
KdTree
template<typename PointSource , typename PointTarget , typename NormalT , typename Scalar = float> using pcl::registration::CorrespondenceEstimationNormalShooting< PointSource, PointTarget, NormalT, Scalar >::KdTree = pcl::search::KdTree<PointTarget>
Definition at line 104 of file correspondence_estimation_normal_shooting.h.
KdTreePtr
template<typename PointSource , typename PointTarget , typename NormalT , typename Scalar = float> using pcl::registration::CorrespondenceEstimationNormalShooting< PointSource, PointTarget, NormalT, Scalar >::KdTreePtr = typename KdTree::Ptr
Definition at line 105 of file correspondence_estimation_normal_shooting.h.
NormalsConstPtr
template<typename PointSource , typename PointTarget , typename NormalT , typename Scalar = float> using pcl::registration::CorrespondenceEstimationNormalShooting< PointSource, PointTarget, NormalT, Scalar >::NormalsConstPtr = typename PointCloudNormals::ConstPtr
Definition at line 117 of file correspondence_estimation_normal_shooting.h.
NormalsPtr
template<typename PointSource , typename PointTarget , typename NormalT , typename Scalar = float> using pcl::registration::CorrespondenceEstimationNormalShooting< PointSource, PointTarget, NormalT, Scalar >::NormalsPtr = typename PointCloudNormals::Ptr
Definition at line 116 of file correspondence_estimation_normal_shooting.h.
PointCloudNormals
template<typename PointSource , typename PointTarget , typename NormalT , typename Scalar = float> using pcl::registration::CorrespondenceEstimationNormalShooting< PointSource, PointTarget, NormalT, Scalar >::PointCloudNormals = pcl::PointCloud<NormalT>
Definition at line 115 of file correspondence_estimation_normal_shooting.h.
PointCloudSource
template<typename PointSource , typename PointTarget , typename NormalT , typename Scalar = float> using pcl::registration::CorrespondenceEstimationNormalShooting< PointSource, PointTarget, NormalT, Scalar >::PointCloudSource = pcl::PointCloud<PointSource>
Definition at line 107 of file correspondence_estimation_normal_shooting.h.
PointCloudSourceConstPtr
template<typename PointSource , typename PointTarget , typename NormalT , typename Scalar = float> using pcl::registration::CorrespondenceEstimationNormalShooting< PointSource, PointTarget, NormalT, Scalar >::PointCloudSourceConstPtr = typename PointCloudSource::ConstPtr
Definition at line 109 of file correspondence_estimation_normal_shooting.h.
PointCloudSourcePtr
template<typename PointSource , typename PointTarget , typename NormalT , typename Scalar = float> using pcl::registration::CorrespondenceEstimationNormalShooting< PointSource, PointTarget, NormalT, Scalar >::PointCloudSourcePtr = typename PointCloudSource::Ptr
Definition at line 108 of file correspondence_estimation_normal_shooting.h.
PointCloudTarget
template<typename PointSource , typename PointTarget , typename NormalT , typename Scalar = float> using pcl::registration::CorrespondenceEstimationNormalShooting< PointSource, PointTarget, NormalT, Scalar >::PointCloudTarget = pcl::PointCloud<PointTarget>
Definition at line 111 of file correspondence_estimation_normal_shooting.h.
PointCloudTargetConstPtr
template<typename PointSource , typename PointTarget , typename NormalT , typename Scalar = float> using pcl::registration::CorrespondenceEstimationNormalShooting< PointSource, PointTarget, NormalT, Scalar >::PointCloudTargetConstPtr = typename PointCloudTarget::ConstPtr
Definition at line 113 of file correspondence_estimation_normal_shooting.h.
PointCloudTargetPtr
template<typename PointSource , typename PointTarget , typename NormalT , typename Scalar = float> using pcl::registration::CorrespondenceEstimationNormalShooting< PointSource, PointTarget, NormalT, Scalar >::PointCloudTargetPtr = typename PointCloudTarget::Ptr
Definition at line 112 of file correspondence_estimation_normal_shooting.h.
Ptr
template<typename PointSource , typename PointTarget , typename NormalT , typename Scalar = float> using pcl::registration::CorrespondenceEstimationNormalShooting< PointSource, PointTarget, NormalT, Scalar >::Ptr = shared_ptr<CorrespondenceEstimationNormalShooting<PointSource, PointTarget, NormalT, Scalar> >
Definition at line 82 of file correspondence_estimation_normal_shooting.h.
Constructor & Destructor Documentation
CorrespondenceEstimationNormalShooting()
template<typename PointSource , typename PointTarget , typename NormalT , typename Scalar = float> pcl::registration::CorrespondenceEstimationNormalShooting< PointSource, PointTarget, NormalT, Scalar >::CorrespondenceEstimationNormalShooting () inline
Empty constructor.
Note
Sets the number of neighbors to be considered in the target point cloud (k_) to 10.
Definition at line 124 of file correspondence_estimation_normal_shooting.h.
References pcl::registration::CorrespondenceEstimationBase< PointSource, PointTarget, float >::corr_name_.
~CorrespondenceEstimationNormalShooting()
template<typename PointSource , typename PointTarget , typename NormalT , typename Scalar = float> pcl::registration::CorrespondenceEstimationNormalShooting< PointSource, PointTarget, NormalT, Scalar >::~CorrespondenceEstimationNormalShooting () override default
Empty destructor.
Member Function Documentation
clone()
template<typename PointSource , typename PointTarget , typename NormalT , typename Scalar = float> CorrespondenceEstimationBase<PointSource, PointTarget, Scalar>::Ptr pcl::registration::CorrespondenceEstimationNormalShooting< PointSource, PointTarget, NormalT, Scalar >::clone () const inline override virtual
Clone and cast to CorrespondenceEstimationBase.
Implements pcl::registration::CorrespondenceEstimationBase< PointSource, PointTarget, float >.
Definition at line 213 of file correspondence_estimation_normal_shooting.h.
determineCorrespondences()
template<typename PointSource , typename PointTarget , typename NormalT , typename Scalar > void pcl::registration::CorrespondenceEstimationNormalShooting< PointSource, PointTarget, NormalT, Scalar >::determineCorrespondences (pcl::Correspondences & correspondences, double max_distance = std::numeric_limits<double>::max()) override virtual
Determine the correspondences between input and target cloud.
Parameters
[out] correspondences the found correspondences (index of query point, index of target point, distance)
[in] max_distance maximum distance between the normal on the source point cloud and the corresponding point in the target point cloud
Implements pcl::registration::CorrespondenceEstimationBase< PointSource, PointTarget, float >.
Definition at line 68 of file correspondence_estimation_normal_shooting.hpp.
References pcl::copyPoint(), pcl::Correspondence::distance, pcl::Correspondence::index_match, and pcl::Correspondence::index_query.
determineReciprocalCorrespondences()
template<typename PointSource , typename PointTarget , typename NormalT , typename Scalar > void pcl::registration::CorrespondenceEstimationNormalShooting< PointSource, PointTarget, NormalT, Scalar >::determineReciprocalCorrespondences (pcl::Correspondences & correspondences, double max_distance = std::numeric_limits<double>::max()) override virtual
Determine the reciprocal correspondences between input and target cloud.
A correspondence is considered reciprocal if both Src_i has Tgt_i as a correspondence, and Tgt_i has Src_i as one.
Parameters
[out] correspondences the found correspondences (index of query and target point, distance)
[in] max_distance maximum allowed distance between correspondences
Implements pcl::registration::CorrespondenceEstimationBase< PointSource, PointTarget, float >.
Definition at line 177 of file correspondence_estimation_normal_shooting.hpp.
References pcl::copyPoint(), pcl::Correspondence::distance, pcl::Correspondence::index_match, and pcl::Correspondence::index_query.
getKSearch()
template<typename PointSource , typename PointTarget , typename NormalT , typename Scalar = float> unsigned int pcl::registration::CorrespondenceEstimationNormalShooting< PointSource, PointTarget, NormalT, Scalar >::getKSearch () const inline
Get the number of nearest neighbours considered in the target point cloud for computing correspondences.
By default we use k = 10 nearest neighbors.
Definition at line 206 of file correspondence_estimation_normal_shooting.h.
getSourceNormals()
template<typename PointSource , typename PointTarget , typename NormalT , typename Scalar = float> NormalsConstPtr pcl::registration::CorrespondenceEstimationNormalShooting< PointSource, PointTarget, NormalT, Scalar >::getSourceNormals () const inline
Get the normals of the source point cloud.
Definition at line 145 of file correspondence_estimation_normal_shooting.h.
initCompute()
template<typename PointSource , typename PointTarget , typename NormalT , typename Scalar > bool pcl::registration::CorrespondenceEstimationNormalShooting< PointSource, PointTarget, NormalT, Scalar >::initCompute protected
Internal computation initialization.
Definition at line 52 of file correspondence_estimation_normal_shooting.hpp.
requiresSourceNormals()
template<typename PointSource , typename PointTarget , typename NormalT , typename Scalar = float> bool pcl::registration::CorrespondenceEstimationNormalShooting< PointSource, PointTarget, NormalT, Scalar >::requiresSourceNormals () const inline override virtual
See if this rejector requires source normals.
Reimplemented from pcl::registration::CorrespondenceEstimationBase< PointSource, PointTarget, float >.
Definition at line 152 of file correspondence_estimation_normal_shooting.h.
setKSearch()
template<typename PointSource , typename PointTarget , typename NormalT , typename Scalar = float> void pcl::registration::CorrespondenceEstimationNormalShooting< PointSource, PointTarget, NormalT, Scalar >::setKSearch (unsigned int k) inline
Set the number of nearest neighbours to be considered in the target point cloud.
By default, we use k = 10 nearest neighbors.
Parameters
[in] k the number of nearest neighbours to be considered
Definition at line 196 of file correspondence_estimation_normal_shooting.h.
setSourceNormals() [1/2]
template<typename PointSource , typename PointTarget , typename NormalT , typename Scalar = float> void pcl::registration::CorrespondenceEstimationNormalShooting< PointSource, PointTarget, NormalT, Scalar >::setSourceNormals (const NormalsConstPtr & normals) inline
Set the normals computed on the source point cloud.
Parameters
[in] normals the normals computed for the source cloud
Definition at line 137 of file correspondence_estimation_normal_shooting.h.
Referenced by pcl::registration::CorrespondenceEstimationNormalShooting< PointSource, PointTarget, NormalT, Scalar >::setSourceNormals().
setSourceNormals() [2/2]
template<typename PointSource , typename PointTarget , typename NormalT , typename Scalar = float> void pcl::registration::CorrespondenceEstimationNormalShooting< PointSource, PointTarget, NormalT, Scalar >::setSourceNormals (pcl::PCLPointCloud2::ConstPtr cloud2) inline override virtual
Blob method for setting the source normals.
Reimplemented from pcl::registration::CorrespondenceEstimationBase< PointSource, PointTarget, float >.
Definition at line 159 of file correspondence_estimation_normal_shooting.h.
References pcl::fromPCLPointCloud2(), and pcl::registration::CorrespondenceEstimationNormalShooting< PointSource, PointTarget, NormalT, Scalar >::setSourceNormals().
The documentation for this class was generated from the following files:
pcl/registration/correspondence_estimation_normal_shooting.h
pcl/registration/impl/correspondence_estimation_normal_shooting.hpp
© 20092012, Willow Garage, Inc.
© 2012, Open Perception, Inc.
Licensed under the BSD License.
https://pointclouds.org/documentation/classpcl_1_1registration_1_1_correspondence_estimation_normal_shooting.html