Normal vector refinement class
#include <pcl/filters/normal_refinement.h>
Public Member Functions
NormalRefinement ()
Empty constructor, sets default convergence parameters.
NormalRefinement (const std::vector< Indices > &k_indices, const std::vector< std::vector< float > > &k_sqr_distances)
Constructor for setting correspondences, sets default convergence parameters.
void setCorrespondences (const std::vector< Indices > &k_indices, const std::vector< std::vector< float > > &k_sqr_distances)
Set correspondences calculated from nearest neighbor search.
void getCorrespondences (std::vector< Indices > &k_indices, std::vector< std::vector< float > > &k_sqr_distances)
Get correspondences (copy)
void setMaxIterations (unsigned int max_iterations)
Set maximum iterations.
unsigned int getMaxIterations ()
Get maximum iterations.
void setConvergenceThreshold (float convergence_threshold)
Set convergence threshold.
float getConvergenceThreshold ()
Get convergence threshold.
Public Member Functions inherited from pcl::Filter< NormalT >
Filter (bool extract_removed_indices=false)
Empty constructor.
IndicesConstPtr const getRemovedIndices () const
Get the point indices being removed.
void getRemovedIndices (PointIndices &pi)
Get the point indices being removed.
void filter (PointCloud &output)
Calls the filtering method and returns the filtered dataset in output.
Public Member Functions inherited from pcl::PCLBase< PointT >
PCLBase ()
Empty constructor.
PCLBase (const PCLBase &base)
Copy constructor.
virtual ~PCLBase ()=default
Destructor.
virtual void setInputCloud (const PointCloudConstPtr &cloud)
Provide a pointer to the input dataset.
PointCloudConstPtr const getInputCloud () const
Get a pointer to the input point cloud dataset.
virtual void setIndices (const IndicesPtr &indices)
Provide a pointer to the vector of indices that represents the input data.
virtual void setIndices (const IndicesConstPtr &indices)
Provide a pointer to the vector of indices that represents the input data.
virtual void setIndices (const PointIndicesConstPtr &indices)
Provide a pointer to the vector of indices that represents the input data.
virtual void setIndices (std::size_t row_start, std::size_t col_start, std::size_t nb_rows, std::size_t nb_cols)
Set the indices for the points laying within an interest region of the point cloud.
IndicesPtr getIndices ()
Get a pointer to the vector of indices used.
IndicesConstPtr const getIndices () const
Get a pointer to the vector of indices used.
const PointT & operator[] (std::size_t pos) const
Override PointCloud operator[] to shorten code.
Protected Member Functions
void applyFilter (PointCloud &output) override
Filter a Point Cloud.
Protected Member Functions inherited from pcl::Filter< NormalT >
const std::string & getClassName () const
Get a string representation of the name of this class.
Protected Member Functions inherited from pcl::PCLBase< PointT >
bool initCompute ()
This method should get called before starting the actual computation.
bool deinitCompute ()
This method should get called after finishing the actual computation.
Additional Inherited Members
Public Types inherited from pcl::Filter< NormalT >
using Ptr = shared_ptr< Filter< NormalT > >
using ConstPtr = shared_ptr< const Filter< NormalT > >
using PointCloud = pcl::PointCloud< NormalT >
using PointCloudPtr = typename PointCloud::Ptr
using PointCloudConstPtr = typename PointCloud::ConstPtr
Public Types inherited from pcl::PCLBase< PointT >
using PointCloud = pcl::PointCloud< PointT >
using PointCloudPtr = typename PointCloud::Ptr
using PointCloudConstPtr = typename PointCloud::ConstPtr
using PointIndicesPtr = PointIndices::Ptr
using PointIndicesConstPtr = PointIndices::ConstPtr
Protected Attributes inherited from pcl::Filter< NormalT >
IndicesPtr removed_indices_
Indices of the points that are removed.
std::string filter_name_
The filter name.
bool extract_removed_indices_
Set to true if we want to return the indices of the removed points.
Protected Attributes inherited from pcl::PCLBase< PointT >
PointCloudConstPtr input_
The input point cloud dataset.
IndicesPtr indices_
A pointer to the vector of point indices to use.
bool use_indices_
Set to true if point indices are used.
bool fake_indices_
If no set of indices are given, we construct a set of fake indices that mimic the input PointCloud.
Detailed Description
template<typename NormalT>
class pcl::NormalRefinement< NormalT >
Normal vector refinement class
This class refines a set of already estimated normals by iteratively updating each normal to the (weighted) mean of all normals in its neighborhood. The intention is that you reuse the same point correspondences as used when estimating the original normals in order to avoid repeating a nearest neighbor search.
Note
This class avoids points for which a NaN is encountered in the neighborhood. In the special case where a point has only NaNs in its neighborhood, the resultant refined normal will be set to zero, i.e. this class only produces finite normals.
Usage example:
// Input point cloud
pcl::PointCloud<PointT> cloud;
// Fill cloud...
// Estimated and refined normals
pcl::PointCloud<NormalT> normals;
pcl::PointCloud<NormalT> normals_refined;
// Search parameters
const int k = 5;
std::vector<Indices > k_indices;
std::vector<std::vector<float> > k_sqr_distances;
// Run search
pcl::search::KdTree<pcl::PointXYZRGB> search;
search.setInputCloud (cloud.makeShared ());
search.nearestKSearch (cloud, Indices (), k, k_indices, k_sqr_distances);
// Use search results for normal estimation
pcl::NormalEstimation<PointT, NormalT> ne;
for (unsigned int i = 0; i < cloud.size (); ++i)
{
 NormalT normal;
 ne.computePointNormal (cloud, k_indices[i]
 normal.normal_x, normal.normal_y, normal.normal_z, normal.curvature);
 pcl::flipNormalTowardsViewpoint (cloud[i], cloud.sensor_origin_[0], cloud.sensor_origin_[1], cloud.sensor_origin_[2],
 normal.normal_x, normal.normal_y, normal.normal_z);
 normals.push_back (normal);
}
// Run refinement using search results
pcl::NormalRefinement<NormalT> nr (k_indices, k_sqr_distances);
nr.setInputCloud (normals.makeShared ());
nr.filter (normals_refined);
pcl::NormalEstimationNormalEstimation estimates local surface properties (surface normals and curvatures)at each 3D point.Definition: normal_3d.h:244
pcl::NormalEstimation
NormalEstimation estimates local surface properties (surface normals and curvatures)at each 3D point.
Definition: normal_3d.h:244
pcl::NormalEstimation::computePointNormalbool computePointNormal(const pcl::PointCloud< PointInT > &cloud, const pcl::Indices &indices, Eigen::Vector4f &plane_parameters, float &curvature)Compute the Least-Squares plane fit for a given set of points, using their indices,...Definition: normal_3d.h:284
pcl::NormalEstimation::computePointNormal
bool computePointNormal(const pcl::PointCloud< PointInT > &cloud, const pcl::Indices &indices, Eigen::Vector4f &plane_parameters, float &curvature)
Compute the Least-Squares plane fit for a given set of points, using their indices,...
Definition: normal_3d.h:284
pcl::NormalRefinementNormal vector refinement classDefinition: normal_refinement.h:191
pcl::NormalRefinement
Normal vector refinement class
Definition: normal_refinement.h:191
pcl::PointCloudPointCloud represents the base class in PCL for storing collections of 3D points.Definition: point_cloud.h:173
pcl::PointCloud
PointCloud represents the base class in PCL for storing collections of 3D points.
Definition: point_cloud.h:173
pcl::PointCloud::push_backvoid push_back(const PointT &pt)Insert a new point in the cloud, at the end of the container.Definition: point_cloud.h:663
pcl::PointCloud::push_back
void push_back(const PointT &pt)
Insert a new point in the cloud, at the end of the container.
Definition: point_cloud.h:663
pcl::PointCloud::sizestd::size_t size() constDefinition: point_cloud.h:443
pcl::PointCloud::size
std::size_t size() const
Definition: point_cloud.h:443
pcl::PointCloud::sensor_origin_Eigen::Vector4f sensor_origin_Sensor acquisition pose (origin/translation).Definition: point_cloud.h:406
pcl::PointCloud::sensor_origin_
Eigen::Vector4f sensor_origin_
Sensor acquisition pose (origin/translation).
Definition: point_cloud.h:406
pcl::PointCloud::makeSharedPtr makeShared() constCopy the cloud to the heap and return a smart pointer Note that deep copy is performed,...Definition: point_cloud.h:898
pcl::PointCloud::makeShared
Ptr makeShared() const
Copy the cloud to the heap and return a smart pointer Note that deep copy is performed,...
Definition: point_cloud.h:898
pcl::search::KdTree< pcl::PointXYZRGB >
pcl::search::KdTree< pcl::PointXYZRGB >
pcl::search::KdTree::nearestKSearchint nearestKSearch(const PointT &point, int k, Indices &k_indices, std::vector< float > &k_sqr_distances) const overrideSearch for the k-nearest neighbors for the given query point.Definition: kdtree.hpp:87
pcl::search::KdTree::nearestKSearch
int nearestKSearch(const PointT &point, int k, Indices &k_indices, std::vector< float > &k_sqr_distances) const override
Search for the k-nearest neighbors for the given query point.
Definition: kdtree.hpp:87
pcl::search::KdTree::setInputCloudvoid setInputCloud(const PointCloudConstPtr &cloud, const IndicesConstPtr &indices=IndicesConstPtr()) overrideProvide a pointer to the input dataset.Definition: kdtree.hpp:76
pcl::search::KdTree::setInputCloud
void setInputCloud(const PointCloudConstPtr &cloud, const IndicesConstPtr &indices=IndicesConstPtr()) override
Provide a pointer to the input dataset.
Definition: kdtree.hpp:76
pcl::flipNormalTowardsViewpointvoid flipNormalTowardsViewpoint(const PointT &point, float vp_x, float vp_y, float vp_z, Eigen::Matrix< Scalar, 4, 1 > &normal)Flip (in place) the estimated normal of a point towards a given viewpoint.Definition: normal_3d.h:122
pcl::flipNormalTowardsViewpoint
void flipNormalTowardsViewpoint(const PointT &point, float vp_x, float vp_y, float vp_z, Eigen::Matrix< Scalar, 4, 1 > &normal)
Flip (in place) the estimated normal of a point towards a given viewpoint.
Definition: normal_3d.h:122
pcl::IndicesIndicesAllocator<> IndicesType used for indices in PCL.Definition: types.h:133
pcl::Indices
IndicesAllocator<> Indices
Type used for indices in PCL.
Definition: types.h:133
pcl::_Normal::curvaturefloat curvatureDefinition: point_types.hpp:809
pcl::_Normal::curvature
float curvature
Definition: point_types.hpp:809
pcl::NormalA point structure representing normal coordinates and the surface curvature estimate.Definition: point_types.hpp:821
pcl::Normal
A point structure representing normal coordinates and the surface curvature estimate.
Definition: point_types.hpp:821
Author
Anders Glent Buch
Definition at line 190 of file normal_refinement.h.
Constructor & Destructor Documentation
NormalRefinement() [1/2]
template<typename NormalT > pcl::NormalRefinement< NormalT >::NormalRefinement () inline
Empty constructor, sets default convergence parameters.
Definition at line 203 of file normal_refinement.h.
References pcl::Filter< NormalT >::filter_name_, pcl::NormalRefinement< NormalT >::setConvergenceThreshold(), and pcl::NormalRefinement< NormalT >::setMaxIterations().
NormalRefinement() [2/2]
template<typename NormalT > pcl::NormalRefinement< NormalT >::NormalRefinement (const std::vector< Indices > & k_indices, const std::vector< std::vector< float > > & k_sqr_distances) inline
Constructor for setting correspondences, sets default convergence parameters.
Parameters
k_indices indices of neighboring points
k_sqr_distances squared distances to the neighboring points
Definition at line 215 of file normal_refinement.h.
References pcl::Filter< NormalT >::filter_name_, pcl::NormalRefinement< NormalT >::setConvergenceThreshold(), pcl::NormalRefinement< NormalT >::setCorrespondences(), and pcl::NormalRefinement< NormalT >::setMaxIterations().
Member Function Documentation
applyFilter()
template<typename NormalT > void pcl::NormalRefinement< NormalT >::applyFilter (PointCloud & output) override protected virtual
Filter a Point Cloud.
Parameters
output the resultant point cloud message
Implements pcl::Filter< NormalT >.
Definition at line 48 of file normal_refinement.hpp.
References pcl::refineNormal().
getConvergenceThreshold()
template<typename NormalT > float pcl::NormalRefinement< NormalT >::getConvergenceThreshold () inline
Get convergence threshold.
Returns
convergence threshold
Definition at line 277 of file normal_refinement.h.
getCorrespondences()
template<typename NormalT > void pcl::NormalRefinement< NormalT >::getCorrespondences (std::vector< Indices > & k_indices, std::vector< std::vector< float > > & k_sqr_distances) inline
Get correspondences (copy)
Parameters
k_indices indices of neighboring points
k_sqr_distances squared distances to the neighboring points
Definition at line 240 of file normal_refinement.h.
getMaxIterations()
template<typename NormalT > unsigned int pcl::NormalRefinement< NormalT >::getMaxIterations () inline
Get maximum iterations.
Returns
maximum iterations
Definition at line 259 of file normal_refinement.h.
setConvergenceThreshold()
template<typename NormalT > void pcl::NormalRefinement< NormalT >::setConvergenceThreshold (float convergence_threshold) inline
Set convergence threshold.
Parameters
convergence_threshold convergence threshold
Definition at line 268 of file normal_refinement.h.
Referenced by pcl::NormalRefinement< NormalT >::NormalRefinement().
setCorrespondences()
template<typename NormalT > void pcl::NormalRefinement< NormalT >::setCorrespondences (const std::vector< Indices > & k_indices, const std::vector< std::vector< float > > & k_sqr_distances) inline
Set correspondences calculated from nearest neighbor search.
Parameters
k_indices indices of neighboring points
k_sqr_distances squared distances to the neighboring points
Definition at line 229 of file normal_refinement.h.
Referenced by pcl::NormalRefinement< NormalT >::NormalRefinement().
setMaxIterations()
template<typename NormalT > void pcl::NormalRefinement< NormalT >::setMaxIterations (unsigned int max_iterations) inline
Set maximum iterations.
Parameters
max_iterations maximum iterations
Definition at line 250 of file normal_refinement.h.
Referenced by pcl::NormalRefinement< NormalT >::NormalRefinement().
The documentation for this class was generated from the following files:
pcl/filters/normal_refinement.h
pcl/filters/impl/normal_refinement.hpp
© 20092012, Willow Garage, Inc.
© 2012, Open Perception, Inc.
Licensed under the BSD License.
https://pointclouds.org/documentation/classpcl_1_1_normal_refinement.html