SampleConsensus represents the base class.
#include <pcl/sample_consensus/sac.h>
Public Types
using Ptr = shared_ptr< SampleConsensus< T > >
using ConstPtr = shared_ptr< const SampleConsensus< T > >
Public Member Functions
SampleConsensus (const SampleConsensusModelPtr &model, bool random=false)
Constructor for base SAC.
SampleConsensus (const SampleConsensusModelPtr &model, double threshold, bool random=false)
Constructor for base SAC.
void setSampleConsensusModel (const SampleConsensusModelPtr &model)
Set the Sample Consensus model to use.
SampleConsensusModelPtr getSampleConsensusModel () const
Get the Sample Consensus model used.
virtual ~SampleConsensus ()=default
Destructor for base SAC.
void setDistanceThreshold (double threshold)
Set the distance to model threshold.
double getDistanceThreshold () const
Get the distance to model threshold, as set by the user.
void setMaxIterations (int max_iterations)
Set the maximum number of iterations.
int getMaxIterations () const
Get the maximum number of iterations, as set by the user.
void setProbability (double probability)
Set the desired probability of choosing at least one sample free from outliers.
double getProbability () const
Obtain the probability of choosing at least one sample free from outliers, as set by the user.
void setNumberOfThreads (const int nr_threads=-1)
Set the number of threads to use or turn off parallelization.
int getNumberOfThreads () const
Get the number of threads, as set by the user.
virtual bool computeModel (int debug_verbosity_level=0)=0
Compute the actual model.
virtual bool refineModel (const double sigma=3.0, const unsigned int max_iterations=1000)
Refine the model found.
void getRandomSamples (const IndicesPtr &indices, std::size_t nr_samples, std::set< index_t > &indices_subset)
Get a set of randomly selected indices.
void getModel (Indices &model) const
Return the best model found so far.
void getInliers (Indices &inliers) const
Return the best set of inliers found so far for this model.
void getModelCoefficients (Eigen::VectorXf &model_coefficients) const
Return the model coefficients of the best model found so far.
Protected Member Functions
double rnd ()
Boost-based random number generator.
Protected Attributes
SampleConsensusModelPtr sac_model_
The underlying data model used (i.e.
Indices model_
The model found after the last computeModel () as point cloud indices.
Indices inliers_
The indices of the points that were chosen as inliers after the last computeModel () call.
Eigen::VectorXf model_coefficients_
The coefficients of our model computed directly from the model found.
double probability_
Desired probability of choosing at least one sample free from outliers.
int iterations_
Total number of internal loop iterations that we've done so far.
double threshold_
Distance to model threshold.
int max_iterations_
Maximum number of iterations before giving up.
int threads_
The number of threads the scheduler should use, or a negative number if no parallelization is wanted.
boost::mt19937 rng_alg_
Boost-based random number generator algorithm.
std::shared_ptr< boost::uniform_01< boost::mt19937 > > rng_
Boost-based random number generator distribution.
Detailed Description
template<typename T>
class pcl::SampleConsensus< T >
SampleConsensus represents the base class.
All sample consensus methods must inherit from this class.
Author
Radu Bogdan Rusu
Definition at line 60 of file sac.h.
Member Typedef Documentation
ConstPtr
template<typename T > using pcl::SampleConsensus< T >::ConstPtr = shared_ptr<const SampleConsensus<T> >
Definition at line 70 of file sac.h.
Ptr
template<typename T > using pcl::SampleConsensus< T >::Ptr = shared_ptr<SampleConsensus<T> >
Definition at line 69 of file sac.h.
Constructor & Destructor Documentation
SampleConsensus() [1/2]
template<typename T > pcl::SampleConsensus< T >::SampleConsensus (const SampleConsensusModelPtr & model, bool random = false) inline
Constructor for base SAC.
Parameters
[in] model a Sample Consensus model
[in] random if true set the random seed to the current time, else set to 12345 (default: false)
Definition at line 77 of file sac.h.
References pcl::SampleConsensus< T >::rng_.
SampleConsensus() [2/2]
template<typename T > pcl::SampleConsensus< T >::SampleConsensus (const SampleConsensusModelPtr & model, double threshold, bool random = false) inline
Constructor for base SAC.
Parameters
[in] model a Sample Consensus model
[in] threshold distance to model threshold
[in] random if true set the random seed to the current time, else set to 12345 (default: false)
Definition at line 98 of file sac.h.
References pcl::SampleConsensus< T >::rng_.
~SampleConsensus()
template<typename T > virtual pcl::SampleConsensus< T >::~SampleConsensus () virtual default
Destructor for base SAC.
Member Function Documentation
computeModel()
template<typename T > virtual bool pcl::SampleConsensus< T >::computeModel (int debug_verbosity_level = 0) pure virtual
Compute the actual model.
Pure virtual.
Implemented in pcl::RandomizedRandomSampleConsensus< PointT >, pcl::RandomizedMEstimatorSampleConsensus< PointT >, pcl::RandomSampleConsensus< PointT >, pcl::ProgressiveSampleConsensus< PointT >, pcl::MEstimatorSampleConsensus< PointT >, pcl::MaximumLikelihoodSampleConsensus< PointT >, and pcl::LeastMedianSquares< PointT >.
getDistanceThreshold()
template<typename T > double pcl::SampleConsensus< T >::getDistanceThreshold () const inline
Get the distance to model threshold, as set by the user.
Definition at line 143 of file sac.h.
References pcl::SampleConsensus< T >::threshold_.
getInliers()
template<typename T > void pcl::SampleConsensus< T >::getInliers (Indices & inliers) const inline
Return the best set of inliers found so far for this model.
Parameters
[out] inliers the resultant set of inliers
Definition at line 310 of file sac.h.
References pcl::SampleConsensus< T >::inliers_.
Referenced by pcl::registration::CorrespondenceRejectorSampleConsensus2D< PointT >::getRemainingCorrespondences(), and pcl::registration::CorrespondenceRejectorSampleConsensus< PointT >::getRemainingCorrespondences().
getMaxIterations()
template<typename T > int pcl::SampleConsensus< T >::getMaxIterations () const inline
Get the maximum number of iterations, as set by the user.
Definition at line 153 of file sac.h.
References pcl::SampleConsensus< T >::max_iterations_.
getModel()
template<typename T > void pcl::SampleConsensus< T >::getModel (Indices & model) const inline
Return the best model found so far.
Parameters
[out] model the resultant model
Definition at line 304 of file sac.h.
References pcl::SampleConsensus< T >::model_.
getModelCoefficients()
template<typename T > void pcl::SampleConsensus< T >::getModelCoefficients (Eigen::VectorXf & model_coefficients) const inline
Return the model coefficients of the best model found so far.
Parameters
[out] model_coefficients the resultant model coefficients, as documented in Module sample_consensus
Definition at line 316 of file sac.h.
References pcl::SampleConsensus< T >::model_coefficients_.
Referenced by pcl::registration::CorrespondenceRejectorSampleConsensus2D< PointT >::getRemainingCorrespondences(), and pcl::registration::CorrespondenceRejectorSampleConsensus< PointT >::getRemainingCorrespondences().
getNumberOfThreads()
template<typename T > int pcl::SampleConsensus< T >::getNumberOfThreads () const inline
Get the number of threads, as set by the user.
Definition at line 175 of file sac.h.
References pcl::SampleConsensus< T >::threads_.
getProbability()
template<typename T > double pcl::SampleConsensus< T >::getProbability () const inline
Obtain the probability of choosing at least one sample free from outliers, as set by the user.
Definition at line 164 of file sac.h.
References pcl::SampleConsensus< T >::probability_.
getRandomSamples()
template<typename T > void pcl::SampleConsensus< T >::getRandomSamples (const IndicesPtr & indices, std::size_t nr_samples, std::set< index_t > & indices_subset) inline
Get a set of randomly selected indices.
Parameters
[in] indices the input indices vector
[in] nr_samples the desired number of point indices to randomly select
[out] indices_subset the resultant output set of randomly selected indices
Definition at line 290 of file sac.h.
References pcl::SampleConsensus< T >::rnd().
getSampleConsensusModel()
template<typename T > SampleConsensusModelPtr pcl::SampleConsensus< T >::getSampleConsensusModel () const inline
Get the Sample Consensus model used.
Definition at line 127 of file sac.h.
References pcl::SampleConsensus< T >::sac_model_.
refineModel()
template<typename T > virtual bool pcl::SampleConsensus< T >::refineModel (const double sigma = 3.0, const unsigned int max_iterations = 1000) inline virtual
Refine the model found.
This loops over the model coefficients and optimizes them together with the set of inliers, until the change in the set of inliers is minimal.
Parameters
[in] sigma standard deviation multiplier for considering a sample as inlier (Mahalanobis distance)
[in] max_iterations the maxim number of iterations to try to refine in case the inliers keep on changing
Definition at line 189 of file sac.h.
References pcl::SampleConsensus< T >::inliers_, pcl::SampleConsensus< T >::model_coefficients_, pcl::SampleConsensus< T >::sac_model_, and pcl::SampleConsensus< T >::threshold_.
Referenced by pcl::registration::CorrespondenceRejectorSampleConsensus2D< PointT >::getRemainingCorrespondences(), and pcl::registration::CorrespondenceRejectorSampleConsensus< PointT >::getRemainingCorrespondences().
rnd()
template<typename T > double pcl::SampleConsensus< T >::rnd () inline protected
Boost-based random number generator.
Definition at line 354 of file sac.h.
References pcl::SampleConsensus< T >::rng_.
Referenced by pcl::SampleConsensus< T >::getRandomSamples().
setDistanceThreshold()
template<typename T > void pcl::SampleConsensus< T >::setDistanceThreshold (double threshold) inline
Set the distance to model threshold.
Parameters
[in] threshold distance to model threshold
Definition at line 139 of file sac.h.
References pcl::SampleConsensus< T >::threshold_.
setMaxIterations()
template<typename T > void pcl::SampleConsensus< T >::setMaxIterations (int max_iterations) inline
Set the maximum number of iterations.
Parameters
[in] max_iterations maximum number of iterations
Definition at line 149 of file sac.h.
References pcl::SampleConsensus< T >::max_iterations_.
Referenced by pcl::registration::CorrespondenceRejectorSampleConsensus2D< PointT >::getRemainingCorrespondences(), and pcl::registration::CorrespondenceRejectorSampleConsensus< PointT >::getRemainingCorrespondences().
setNumberOfThreads()
template<typename T > void pcl::SampleConsensus< T >::setNumberOfThreads (const int nr_threads = -1) inline
Set the number of threads to use or turn off parallelization.
Parameters
[in] nr_threads the number of hardware threads to use (0 sets the value automatically, a negative number turns parallelization off)
Note
Not all SAC methods have a parallel implementation. Some will ignore this setting.
Definition at line 171 of file sac.h.
References pcl::SampleConsensus< T >::threads_.
setProbability()
template<typename T > void pcl::SampleConsensus< T >::setProbability (double probability) inline
Set the desired probability of choosing at least one sample free from outliers.
Parameters
[in] probability the desired probability of choosing at least one sample free from outliers
Note
internally, the probability is set to 99% (0.99) by default.
Definition at line 160 of file sac.h.
References pcl::SampleConsensus< T >::probability_.
setSampleConsensusModel()
template<typename T > void pcl::SampleConsensus< T >::setSampleConsensusModel (const SampleConsensusModelPtr & model) inline
Set the Sample Consensus model to use.
Parameters
[in] model a Sample Consensus model
Definition at line 120 of file sac.h.
References pcl::SampleConsensus< T >::sac_model_.
Member Data Documentation
inliers_
template<typename T > Indices pcl::SampleConsensus< T >::inliers_ protected
The indices of the points that were chosen as inliers after the last computeModel () call.
Definition at line 326 of file sac.h.
Referenced by pcl::SampleConsensus< T >::getInliers(), and pcl::SampleConsensus< T >::refineModel().
iterations_
template<typename T > int pcl::SampleConsensus< T >::iterations_ protected
Total number of internal loop iterations that we've done so far.
Definition at line 335 of file sac.h.
max_iterations_
template<typename T > int pcl::SampleConsensus< T >::max_iterations_ protected
Maximum number of iterations before giving up.
Definition at line 341 of file sac.h.
Referenced by pcl::SampleConsensus< T >::getMaxIterations(), and pcl::SampleConsensus< T >::setMaxIterations().
model_
template<typename T > Indices pcl::SampleConsensus< T >::model_ protected
The model found after the last computeModel () as point cloud indices.
Definition at line 323 of file sac.h.
Referenced by pcl::SampleConsensus< T >::getModel().
model_coefficients_
template<typename T > Eigen::VectorXf pcl::SampleConsensus< T >::model_coefficients_ protected
The coefficients of our model computed directly from the model found.
Definition at line 329 of file sac.h.
Referenced by pcl::SampleConsensus< T >::getModelCoefficients(), and pcl::SampleConsensus< T >::refineModel().
probability_
template<typename T > double pcl::SampleConsensus< T >::probability_ protected
Desired probability of choosing at least one sample free from outliers.
Definition at line 332 of file sac.h.
Referenced by pcl::SampleConsensus< T >::getProbability(), and pcl::SampleConsensus< T >::setProbability().
rng_
template<typename T > std::shared_ptr<boost::uniform_01<boost::mt19937> > pcl::SampleConsensus< T >::rng_ protected
Boost-based random number generator distribution.
Definition at line 350 of file sac.h.
Referenced by pcl::SampleConsensus< T >::rnd(), and pcl::SampleConsensus< T >::SampleConsensus().
rng_alg_
template<typename T > boost::mt19937 pcl::SampleConsensus< T >::rng_alg_ protected
Boost-based random number generator algorithm.
Definition at line 347 of file sac.h.
sac_model_
template<typename T > SampleConsensusModelPtr pcl::SampleConsensus< T >::sac_model_ protected
The underlying data model used (i.e.
what is it that we attempt to search for).
Definition at line 320 of file sac.h.
Referenced by pcl::SampleConsensus< T >::getSampleConsensusModel(), pcl::SampleConsensus< T >::refineModel(), and pcl::SampleConsensus< T >::setSampleConsensusModel().
threads_
template<typename T > int pcl::SampleConsensus< T >::threads_ protected
The number of threads the scheduler should use, or a negative number if no parallelization is wanted.
Definition at line 344 of file sac.h.
Referenced by pcl::SampleConsensus< T >::getNumberOfThreads(), and pcl::SampleConsensus< T >::setNumberOfThreads().
threshold_
template<typename T > double pcl::SampleConsensus< T >::threshold_ protected
Distance to model threshold.
Definition at line 338 of file sac.h.
Referenced by pcl::SampleConsensus< T >::getDistanceThreshold(), pcl::SampleConsensus< T >::refineModel(), and pcl::SampleConsensus< T >::setDistanceThreshold().
The documentation for this class was generated from the following file:
pcl/sample_consensus/sac.h
© 20092012, Willow Garage, Inc.
© 2012, Open Perception, Inc.
Licensed under the BSD License.
https://pointclouds.org/documentation/classpcl_1_1_sample_consensus.html