BoundaryEstimation estimates whether a set of points is lying on surface boundaries using an angle criterion.
#include <pcl/features/boundary.h>
Public Types
using Ptr = shared_ptr< BoundaryEstimation< PointInT, PointNT, PointOutT > >
using ConstPtr = shared_ptr< const BoundaryEstimation< PointInT, PointNT, PointOutT > >
using PointCloudOut = typename Feature< PointInT, PointOutT >::PointCloudOut
Public Types inherited from pcl::FeatureFromNormals< PointInT, PointNT, PointOutT >
using PointCloudN = pcl::PointCloud< PointNT >
using PointCloudNPtr = typename PointCloudN::Ptr
using PointCloudNConstPtr = typename PointCloudN::ConstPtr
using Ptr = shared_ptr< FeatureFromNormals< PointInT, PointNT, PointOutT > >
using ConstPtr = shared_ptr< const FeatureFromNormals< PointInT, PointNT, PointOutT > >
Public Types inherited from pcl::Feature< PointInT, PointOutT >
using BaseClass = PCLBase< PointInT >
using Ptr = shared_ptr< Feature< PointInT, PointOutT > >
using ConstPtr = shared_ptr< const Feature< PointInT, PointOutT > >
using KdTree = pcl::search::Search< PointInT >
using KdTreePtr = typename KdTree::Ptr
using PointCloudIn = pcl::PointCloud< PointInT >
using PointCloudInPtr = typename PointCloudIn::Ptr
using PointCloudInConstPtr = typename PointCloudIn::ConstPtr
using PointCloudOut = pcl::PointCloud< PointOutT >
using SearchMethod = std::function< int(std::size_t, double, pcl::Indices &, std::vector< float > &)>
using SearchMethodSurface = std::function< int(const PointCloudIn &cloud, std::size_t index, double, pcl::Indices &, std::vector< float > &)>
Public Types inherited from pcl::PCLBase< PointInT >
using PointCloud = pcl::PointCloud< PointInT >
using PointCloudPtr = typename PointCloud::Ptr
using PointCloudConstPtr = typename PointCloud::ConstPtr
using PointIndicesPtr = PointIndices::Ptr
using PointIndicesConstPtr = PointIndices::ConstPtr
Public Member Functions
BoundaryEstimation ()
Empty constructor.
bool isBoundaryPoint (const pcl::PointCloud< PointInT > &cloud, int q_idx, const pcl::Indices &indices, const Eigen::Vector4f &u, const Eigen::Vector4f &v, const float angle_threshold)
Check whether a point is a boundary point in a planar patch of projected points given by indices.
bool isBoundaryPoint (const pcl::PointCloud< PointInT > &cloud, const PointInT &q_point, const pcl::Indices &indices, const Eigen::Vector4f &u, const Eigen::Vector4f &v, const float angle_threshold)
Check whether a point is a boundary point in a planar patch of projected points given by indices.
void setAngleThreshold (float angle)
Set the decision boundary (angle threshold) that marks points as boundary or regular.
float getAngleThreshold ()
Get the decision boundary (angle threshold) as set by the user.
void getCoordinateSystemOnPlane (const PointNT &p_coeff, Eigen::Vector4f &u, Eigen::Vector4f &v)
Get a u-v-n coordinate system that lies on a plane defined by its normal.
Public Member Functions inherited from pcl::FeatureFromNormals< PointInT, PointNT, PointOutT >
FeatureFromNormals ()
Empty constructor.
void setInputNormals (const PointCloudNConstPtr &normals)
Provide a pointer to the input dataset that contains the point normals of the XYZ dataset.
PointCloudNConstPtr getInputNormals () const
Get a pointer to the normals of the input XYZ point cloud dataset.
Public Member Functions inherited from pcl::Feature< PointInT, PointOutT >
Feature ()
Empty constructor.
void setSearchSurface (const PointCloudInConstPtr &cloud)
Provide a pointer to a dataset to add additional information to estimate the features for every point in the input dataset.
PointCloudInConstPtr getSearchSurface () const
Get a pointer to the surface point cloud dataset.
void setSearchMethod (const KdTreePtr &tree)
Provide a pointer to the search object.
KdTreePtr getSearchMethod () const
Get a pointer to the search method used.
double getSearchParameter () const
Get the internal search parameter.
void setKSearch (int k)
Set the number of k nearest neighbors to use for the feature estimation.
int getKSearch () const
get the number of k nearest neighbors used for the feature estimation.
void setRadiusSearch (double radius)
Set the sphere radius that is to be used for determining the nearest neighbors used for the feature estimation.
double getRadiusSearch () const
Get the sphere radius used for determining the neighbors.
void compute (PointCloudOut &output)
Base method for feature estimation for all points given in <setInputCloud (), setIndices ()> using the surface in setSearchSurface () and the spatial locator in setSearchMethod ()
Public Member Functions inherited from pcl::PCLBase< PointInT >
PCLBase ()
Empty constructor.
PCLBase (const PCLBase &base)
Copy constructor.
virtual ~PCLBase ()=default
Destructor.
virtual void setInputCloud (const PointCloudConstPtr &cloud)
Provide a pointer to the input dataset.
PointCloudConstPtr const getInputCloud () const
Get a pointer to the input point cloud dataset.
virtual void setIndices (const IndicesPtr &indices)
Provide a pointer to the vector of indices that represents the input data.
virtual void setIndices (const IndicesConstPtr &indices)
Provide a pointer to the vector of indices that represents the input data.
virtual void setIndices (const PointIndicesConstPtr &indices)
Provide a pointer to the vector of indices that represents the input data.
virtual void setIndices (std::size_t row_start, std::size_t col_start, std::size_t nb_rows, std::size_t nb_cols)
Set the indices for the points laying within an interest region of the point cloud.
IndicesPtr getIndices ()
Get a pointer to the vector of indices used.
IndicesConstPtr const getIndices () const
Get a pointer to the vector of indices used.
const PointInT & operator[] (std::size_t pos) const
Override PointCloud operator[] to shorten code.
Protected Member Functions
void computeFeature (PointCloudOut &output) override
Estimate whether a set of points is lying on surface boundaries using an angle criterion for all points given in <setInputCloud (), setIndices ()> using the surface in setSearchSurface () and the spatial locator in setSearchMethod ()
Protected Member Functions inherited from pcl::FeatureFromNormals< PointInT, PointNT, PointOutT >
virtual bool initCompute ()
This method should get called before starting the actual computation.
Protected Member Functions inherited from pcl::Feature< PointInT, PointOutT >
const std::string & getClassName () const
Get a string representation of the name of this class.
virtual bool deinitCompute ()
This method should get called after ending the actual computation.
int searchForNeighbors (std::size_t index, double parameter, pcl::Indices &indices, std::vector< float > &distances) const
Search for k-nearest neighbors using the spatial locator from setSearchmethod, and the given surface from setSearchSurface.
int searchForNeighbors (const PointCloudIn &cloud, std::size_t index, double parameter, pcl::Indices &indices, std::vector< float > &distances) const
Search for k-nearest neighbors using the spatial locator from setSearchmethod, and the given surface from setSearchSurface.
Protected Member Functions inherited from pcl::PCLBase< PointInT >
bool initCompute ()
This method should get called before starting the actual computation.
bool deinitCompute ()
This method should get called after finishing the actual computation.
Protected Attributes
float angle_threshold_
The decision boundary (angle threshold) that marks points as boundary or regular.
Protected Attributes inherited from pcl::FeatureFromNormals< PointInT, PointNT, PointOutT >
PointCloudNConstPtr normals_
A pointer to the input dataset that contains the point normals of the XYZ dataset.
Protected Attributes inherited from pcl::Feature< PointInT, PointOutT >
std::string feature_name_
The feature name.
SearchMethodSurface search_method_surface_
The search method template for points.
PointCloudInConstPtr surface_
An input point cloud describing the surface that is to be used for nearest neighbors estimation.
KdTreePtr tree_
A pointer to the spatial search object.
double search_parameter_
The actual search parameter (from either search_radius_ or k_).
double search_radius_
The nearest neighbors search radius for each point.
int k_
The number of K nearest neighbors to use for each point.
bool fake_surface_
If no surface is given, we use the input PointCloud as the surface.
Protected Attributes inherited from pcl::PCLBase< PointInT >
PointCloudConstPtr input_
The input point cloud dataset.
IndicesPtr indices_
A pointer to the vector of point indices to use.
bool use_indices_
Set to true if point indices are used.
bool fake_indices_
If no set of indices are given, we construct a set of fake indices that mimic the input PointCloud.
Detailed Description
template<typename PointInT, typename PointNT, typename PointOutT>
class pcl::BoundaryEstimation< PointInT, PointNT, PointOutT >
BoundaryEstimation estimates whether a set of points is lying on surface boundaries using an angle criterion.
The code makes use of the estimated surface normals at each point in the input dataset.
Here's an example for estimating boundary points for a PointXYZ point cloud:
pcl::PointCloud<pcl::PointXYZ>::Ptr cloud (new pcl::PointCloud<pcl::PointXYZ>);
// fill in the cloud data here
pcl::PointCloud<pcl::Normal>::Ptr normals (new pcl::PointCloud<pcl::Normal>);
// estimate normals and fill in \a normals
pcl::PointCloud<pcl::Boundary> boundaries;
pcl::BoundaryEstimation<pcl::PointXYZ, pcl::Normal, pcl::Boundary> est;
est.setInputCloud (cloud);
est.setInputNormals (normals);
est.setRadiusSearch (0.02); // 2cm radius
est.setSearchMethod (typename pcl::search::KdTree<PointXYZ>::Ptr (new pcl::search::KdTree<PointXYZ>)
est.compute (boundaries);
pcl::BoundaryEstimationBoundaryEstimation estimates whether a set of points is lying on surface boundaries using an angle cr...Definition: boundary.h:80
pcl::BoundaryEstimation
BoundaryEstimation estimates whether a set of points is lying on surface boundaries using an angle cr...
Definition: boundary.h:80
pcl::FeatureFromNormals::setInputNormalsvoid setInputNormals(const PointCloudNConstPtr &normals)Provide a pointer to the input dataset that contains the point normals of the XYZ dataset.Definition: feature.h:339
pcl::FeatureFromNormals::setInputNormals
void setInputNormals(const PointCloudNConstPtr &normals)
Provide a pointer to the input dataset that contains the point normals of the XYZ dataset.
Definition: feature.h:339
pcl::Feature::setRadiusSearchvoid setRadiusSearch(double radius)Set the sphere radius that is to be used for determining the nearest neighbors used for the feature e...Definition: feature.h:198
pcl::Feature::setRadiusSearch
void setRadiusSearch(double radius)
Set the sphere radius that is to be used for determining the nearest neighbors used for the feature e...
Definition: feature.h:198
pcl::Feature::setSearchMethodvoid setSearchMethod(const KdTreePtr &tree)Provide a pointer to the search object.Definition: feature.h:164
pcl::Feature::setSearchMethod
void setSearchMethod(const KdTreePtr &tree)
Provide a pointer to the search object.
Definition: feature.h:164
pcl::Feature::computevoid compute(PointCloudOut &output)Base method for feature estimation for all points given in <setInputCloud (), setIndices ()> using th...Definition: feature.hpp:194
pcl::Feature::compute
void compute(PointCloudOut &output)
Base method for feature estimation for all points given in <setInputCloud (), setIndices ()> using th...
Definition: feature.hpp:194
pcl::PCLBase::setInputCloudvirtual void setInputCloud(const PointCloudConstPtr &cloud)Provide a pointer to the input dataset.Definition: pcl_base.hpp:65
pcl::PCLBase::setInputCloud
virtual void setInputCloud(const PointCloudConstPtr &cloud)
Provide a pointer to the input dataset.
Definition: pcl_base.hpp:65
pcl::PointCloud< pcl::PointXYZ >
pcl::PointCloud< pcl::PointXYZ >
pcl::PointCloud::Ptrshared_ptr< PointCloud< PointT > > PtrDefinition: point_cloud.h:413
pcl::PointCloud::Ptr
shared_ptr< PointCloud< PointT > > Ptr
Definition: point_cloud.h:413
pcl::search::KdTreesearch::KdTree is a wrapper class which inherits the pcl::KdTree class for performing search function...Definition: kdtree.h:62
pcl::search::KdTree
search::KdTree is a wrapper class which inherits the pcl::KdTree class for performing search function...
Definition: kdtree.h:62
pcl::search::KdTree::Ptrshared_ptr< KdTree< PointT, Tree > > PtrDefinition: kdtree.h:75
pcl::search::KdTree::Ptr
shared_ptr< KdTree< PointT, Tree > > Ptr
Definition: kdtree.h:75
Attention
The convention for Boundary features is:
if a query point's nearest neighbors cannot be estimated, the boundary feature will be set to NaN (not a number)
it is impossible to estimate a boundary property for a point that doesn't have finite 3D coordinates. Therefore, any point that contains NaN data on x, y, or z, will have its boundary feature property set to NaN.
Author
Radu B. Rusu
Definition at line 79 of file boundary.h.
Member Typedef Documentation
ConstPtr
template<typename PointInT , typename PointNT , typename PointOutT > using pcl::BoundaryEstimation< PointInT, PointNT, PointOutT >::ConstPtr = shared_ptr<const BoundaryEstimation<PointInT, PointNT, PointOutT> >
Definition at line 83 of file boundary.h.
PointCloudOut
template<typename PointInT , typename PointNT , typename PointOutT > using pcl::BoundaryEstimation< PointInT, PointNT, PointOutT >::PointCloudOut = typename Feature<PointInT, PointOutT>::PointCloudOut
Definition at line 96 of file boundary.h.
Ptr
template<typename PointInT , typename PointNT , typename PointOutT > using pcl::BoundaryEstimation< PointInT, PointNT, PointOutT >::Ptr = shared_ptr<BoundaryEstimation<PointInT, PointNT, PointOutT> >
Definition at line 82 of file boundary.h.
Constructor & Destructor Documentation
BoundaryEstimation()
template<typename PointInT , typename PointNT , typename PointOutT > pcl::BoundaryEstimation< PointInT, PointNT, PointOutT >::BoundaryEstimation () inline
Empty constructor.
The angular threshold angle_threshold_ is set to M_PI / 2.0
Definition at line 102 of file boundary.h.
References pcl::Feature< PointInT, PointOutT >::feature_name_.
Member Function Documentation
computeFeature()
template<typename PointInT , typename PointNT , typename PointOutT > void pcl::BoundaryEstimation< PointInT, PointNT, PointOutT >::computeFeature (PointCloudOut & output) override protected virtual
Estimate whether a set of points is lying on surface boundaries using an angle criterion for all points given in <setInputCloud (), setIndices ()> using the surface in setSearchSurface () and the spatial locator in setSearchMethod ()
Parameters
[out] output the resultant point cloud model dataset that contains boundary point estimates
Implements pcl::Feature< PointInT, PointOutT >.
Definition at line 116 of file boundary.hpp.
References pcl::isFinite().
getAngleThreshold()
template<typename PointInT , typename PointNT , typename PointOutT > float pcl::BoundaryEstimation< PointInT, PointNT, PointOutT >::getAngleThreshold () inline
Get the decision boundary (angle threshold) as set by the user.
Definition at line 148 of file boundary.h.
References pcl::BoundaryEstimation< PointInT, PointNT, PointOutT >::angle_threshold_.
getCoordinateSystemOnPlane()
template<typename PointInT , typename PointNT , typename PointOutT > void pcl::BoundaryEstimation< PointInT, PointNT, PointOutT >::getCoordinateSystemOnPlane (const PointNT & p_coeff, Eigen::Vector4f & u, Eigen::Vector4f & v) inline
Get a u-v-n coordinate system that lies on a plane defined by its normal.
Parameters
[in] p_coeff the plane coefficients (containing the plane normal)
[out] u the resultant u direction
[out] v the resultant v direction
Definition at line 159 of file boundary.h.
Referenced by pcl::ISSKeypoint3D< PointInT, PointOutT, NormalT >::getBoundaryPoints().
isBoundaryPoint() [1/2]
template<typename PointInT , typename PointNT , typename PointOutT > bool pcl::BoundaryEstimation< PointInT, PointNT, PointOutT >::isBoundaryPoint (const pcl::PointCloud< PointInT > & cloud, const PointInT & q_point, const pcl::Indices & indices, const Eigen::Vector4f & u, const Eigen::Vector4f & v, const float angle_threshold)
Check whether a point is a boundary point in a planar patch of projected points given by indices.
Note
A coordinate system u-v-n must be computed a-priori using getCoordinateSystemOnPlane
Parameters
[in] cloud a pointer to the input point cloud
[in] q_point a pointer to the query point
[in] indices the estimated point neighbors of the query point
[in] u the u direction
[in] v the v direction
[in] angle_threshold the threshold angle (default)
Definition at line 62 of file boundary.hpp.
References M_PI.
isBoundaryPoint() [2/2]
template<typename PointInT , typename PointNT , typename PointOutT > bool pcl::BoundaryEstimation< PointInT, PointNT, PointOutT >::isBoundaryPoint (const pcl::PointCloud< PointInT > & cloud, int q_idx, const pcl::Indices & indices, const Eigen::Vector4f & u, const Eigen::Vector4f & v, const float angle_threshold)
Check whether a point is a boundary point in a planar patch of projected points given by indices.
Note
A coordinate system u-v-n must be computed a-priori using getCoordinateSystemOnPlane
Parameters
[in] cloud a pointer to the input point cloud
[in] q_idx the index of the query point in cloud
[in] indices the estimated point neighbors of the query point
[in] u the u direction
[in] v the v direction
[in] angle_threshold the threshold angle (default)
Definition at line 51 of file boundary.hpp.
Referenced by pcl::ISSKeypoint3D< PointInT, PointOutT, NormalT >::getBoundaryPoints().
setAngleThreshold()
template<typename PointInT , typename PointNT , typename PointOutT > void pcl::BoundaryEstimation< PointInT, PointNT, PointOutT >::setAngleThreshold (float angle) inline
Set the decision boundary (angle threshold) that marks points as boundary or regular.
(default)
Parameters
[in] angle the angle threshold
Definition at line 141 of file boundary.h.
References pcl::BoundaryEstimation< PointInT, PointNT, PointOutT >::angle_threshold_.
Member Data Documentation
angle_threshold_
template<typename PointInT , typename PointNT , typename PointOutT > float pcl::BoundaryEstimation< PointInT, PointNT, PointOutT >::angle_threshold_ protected
The decision boundary (angle threshold) that marks points as boundary or regular.
(default)
Definition at line 177 of file boundary.h.
Referenced by pcl::BoundaryEstimation< PointInT, PointNT, PointOutT >::getAngleThreshold(), and pcl::BoundaryEstimation< PointInT, PointNT, PointOutT >::setAngleThreshold().
The documentation for this class was generated from the following files:
pcl/features/boundary.h
pcl/features/impl/boundary.hpp
© 20092012, Willow Garage, Inc.
© 2012, Open Perception, Inc.
Licensed under the BSD License.
https://pointclouds.org/documentation/classpcl_1_1_boundary_estimation.html