VFHEstimation estimates the Viewpoint Feature Histogram (VFH) descriptor for a given point cloud dataset containing points and normals.
#include <pcl/features/vfh.h>
Public Types
using PointCloudOut = typename Feature< PointInT, PointOutT >::PointCloudOut
using Ptr = shared_ptr< VFHEstimation< PointInT, PointNT, PointOutT > >
using ConstPtr = shared_ptr< const VFHEstimation< PointInT, PointNT, PointOutT > >
Public Types inherited from pcl::FeatureFromNormals< PointInT, PointNT, pcl::VFHSignature308 >
using PointCloudN = pcl::PointCloud< PointNT >
using PointCloudNPtr = typename PointCloudN::Ptr
using PointCloudNConstPtr = typename PointCloudN::ConstPtr
using Ptr = shared_ptr< FeatureFromNormals< PointInT, PointNT, pcl::VFHSignature308 > >
using ConstPtr = shared_ptr< const FeatureFromNormals< PointInT, PointNT, pcl::VFHSignature308 > >
Public Types inherited from pcl::Feature< PointInT, PointOutT >
using BaseClass = PCLBase< PointInT >
using Ptr = shared_ptr< Feature< PointInT, PointOutT > >
using ConstPtr = shared_ptr< const Feature< PointInT, PointOutT > >
using KdTree = pcl::search::Search< PointInT >
using KdTreePtr = typename KdTree::Ptr
using PointCloudIn = pcl::PointCloud< PointInT >
using PointCloudInPtr = typename PointCloudIn::Ptr
using PointCloudInConstPtr = typename PointCloudIn::ConstPtr
using PointCloudOut = pcl::PointCloud< PointOutT >
using SearchMethod = std::function< int(std::size_t, double, pcl::Indices &, std::vector< float > &)>
using SearchMethodSurface = std::function< int(const PointCloudIn &cloud, std::size_t index, double, pcl::Indices &, std::vector< float > &)>
Public Types inherited from pcl::PCLBase< PointInT >
using PointCloud = pcl::PointCloud< PointInT >
using PointCloudPtr = typename PointCloud::Ptr
using PointCloudConstPtr = typename PointCloud::ConstPtr
using PointIndicesPtr = PointIndices::Ptr
using PointIndicesConstPtr = PointIndices::ConstPtr
Public Member Functions
VFHEstimation ()
Empty constructor.
void computePointSPFHSignature (const Eigen::Vector4f &centroid_p, const Eigen::Vector4f &centroid_n, const pcl::PointCloud< PointInT > &cloud, const pcl::PointCloud< PointNT > &normals, const pcl::Indices &indices)
Estimate the SPFH (Simple Point Feature Histograms) signatures of the angular (f1, f2, f3) and distance (f4) features for a given point from its neighborhood.
void setViewPoint (float vpx, float vpy, float vpz)
Set the viewpoint.
void getViewPoint (float &vpx, float &vpy, float &vpz)
Get the viewpoint.
void setUseGivenNormal (bool use)
Set use_given_normal_.
void setNormalToUse (const Eigen::Vector3f &normal)
Set the normal to use.
void setUseGivenCentroid (bool use)
Set use_given_centroid_.
void setCentroidToUse (const Eigen::Vector3f &centroid)
Set centroid_to_use_.
void setNormalizeBins (bool normalize)
set normalize_bins_
void setNormalizeDistance (bool normalize)
set normalize_distances_
void setFillSizeComponent (bool fill_size)
set size_component_
void compute (PointCloudOut &output)
Overloaded computed method from pcl::Feature.
Public Member Functions inherited from pcl::FeatureFromNormals< PointInT, PointNT, pcl::VFHSignature308 >
FeatureFromNormals ()
Empty constructor.
void setInputNormals (const PointCloudNConstPtr &normals)
Provide a pointer to the input dataset that contains the point normals of the XYZ dataset.
PointCloudNConstPtr getInputNormals () const
Get a pointer to the normals of the input XYZ point cloud dataset.
Public Member Functions inherited from pcl::Feature< PointInT, PointOutT >
Feature ()
Empty constructor.
void setSearchSurface (const PointCloudInConstPtr &cloud)
Provide a pointer to a dataset to add additional information to estimate the features for every point in the input dataset.
PointCloudInConstPtr getSearchSurface () const
Get a pointer to the surface point cloud dataset.
void setSearchMethod (const KdTreePtr &tree)
Provide a pointer to the search object.
KdTreePtr getSearchMethod () const
Get a pointer to the search method used.
double getSearchParameter () const
Get the internal search parameter.
void setKSearch (int k)
Set the number of k nearest neighbors to use for the feature estimation.
int getKSearch () const
get the number of k nearest neighbors used for the feature estimation.
void setRadiusSearch (double radius)
Set the sphere radius that is to be used for determining the nearest neighbors used for the feature estimation.
double getRadiusSearch () const
Get the sphere radius used for determining the neighbors.
void compute (PointCloudOut &output)
Base method for feature estimation for all points given in <setInputCloud (), setIndices ()> using the surface in setSearchSurface () and the spatial locator in setSearchMethod ()
Public Member Functions inherited from pcl::PCLBase< PointInT >
PCLBase ()
Empty constructor.
PCLBase (const PCLBase &base)
Copy constructor.
virtual ~PCLBase ()=default
Destructor.
virtual void setInputCloud (const PointCloudConstPtr &cloud)
Provide a pointer to the input dataset.
PointCloudConstPtr const getInputCloud () const
Get a pointer to the input point cloud dataset.
virtual void setIndices (const IndicesPtr &indices)
Provide a pointer to the vector of indices that represents the input data.
virtual void setIndices (const IndicesConstPtr &indices)
Provide a pointer to the vector of indices that represents the input data.
virtual void setIndices (const PointIndicesConstPtr &indices)
Provide a pointer to the vector of indices that represents the input data.
virtual void setIndices (std::size_t row_start, std::size_t col_start, std::size_t nb_rows, std::size_t nb_cols)
Set the indices for the points laying within an interest region of the point cloud.
IndicesPtr getIndices ()
Get a pointer to the vector of indices used.
IndicesConstPtr const getIndices () const
Get a pointer to the vector of indices used.
const PointInT & operator[] (std::size_t pos) const
Override PointCloud operator[] to shorten code.
Protected Member Functions
bool initCompute () override
This method should get called before starting the actual computation.
Protected Member Functions inherited from pcl::Feature< PointInT, PointOutT >
const std::string & getClassName () const
Get a string representation of the name of this class.
virtual bool deinitCompute ()
This method should get called after ending the actual computation.
int searchForNeighbors (std::size_t index, double parameter, pcl::Indices &indices, std::vector< float > &distances) const
Search for k-nearest neighbors using the spatial locator from setSearchmethod, and the given surface from setSearchSurface.
int searchForNeighbors (const PointCloudIn &cloud, std::size_t index, double parameter, pcl::Indices &indices, std::vector< float > &distances) const
Search for k-nearest neighbors using the spatial locator from setSearchmethod, and the given surface from setSearchSurface.
Protected Member Functions inherited from pcl::PCLBase< PointInT >
bool initCompute ()
This method should get called before starting the actual computation.
bool deinitCompute ()
This method should get called after finishing the actual computation.
Protected Attributes
std::array< Eigen::VectorXf, 4 > hist_f_
Placeholder for the f1 histogram.
Eigen::VectorXf hist_vp_
Placeholder for the vp histogram.
Eigen::Vector4f normal_to_use_
Normal to be used to computed VFH.
Eigen::Vector4f centroid_to_use_
Centroid to be used to computed VFH.
bool use_given_normal_
Use the normal_to_use_.
bool use_given_centroid_
Use the centroid_to_use_.
bool normalize_bins_
Normalize bins by the number the total number of points.
bool normalize_distances_
Normalize the shape distribution component of VFH.
bool size_component_
Activate or deactivate the size component of VFH.
Protected Attributes inherited from pcl::FeatureFromNormals< PointInT, PointNT, pcl::VFHSignature308 >
PointCloudNConstPtr normals_
A pointer to the input dataset that contains the point normals of the XYZ dataset.
Protected Attributes inherited from pcl::Feature< PointInT, PointOutT >
std::string feature_name_
The feature name.
SearchMethodSurface search_method_surface_
The search method template for points.
PointCloudInConstPtr surface_
An input point cloud describing the surface that is to be used for nearest neighbors estimation.
KdTreePtr tree_
A pointer to the spatial search object.
double search_parameter_
The actual search parameter (from either search_radius_ or k_).
double search_radius_
The nearest neighbors search radius for each point.
int k_
The number of K nearest neighbors to use for each point.
bool fake_surface_
If no surface is given, we use the input PointCloud as the surface.
Protected Attributes inherited from pcl::PCLBase< PointInT >
PointCloudConstPtr input_
The input point cloud dataset.
IndicesPtr indices_
A pointer to the vector of point indices to use.
bool use_indices_
Set to true if point indices are used.
bool fake_indices_
If no set of indices are given, we construct a set of fake indices that mimic the input PointCloud.
Detailed Description
template<typename PointInT, typename PointNT, typename PointOutT = pcl::VFHSignature308>
class pcl::VFHEstimation< PointInT, PointNT, PointOutT >
VFHEstimation estimates the Viewpoint Feature Histogram (VFH) descriptor for a given point cloud dataset containing points and normals.
The default VFH implementation uses 45 binning subdivisions for each of the three extended FPFH values, plus another 45 binning subdivisions for the distances between each point and the centroid and 128 binning subdivisions for the viewpoint component, which results in a 308-byte array of float values. These are stored in a pcl::VFHSignature308 point type. A major difference between the PFH/FPFH descriptors and VFH, is that for a given point cloud dataset, only a single VFH descriptor will be estimated (vfhs->size() should be 1), while the resultant PFH/FPFH data will have the same number of entries as the number of points in the cloud.
Note
If you use this code in any academic work, please cite:
R.B. Rusu, G. Bradski, R. Thibaux, J. Hsu. Fast 3D Recognition and Pose Using the Viewpoint Feature Histogram. In Proceedings of International Conference on Intelligent Robots and Systems (IROS) Taipei, Taiwan, October 18-22 2010.
Note
The code is stateful as we do not expect this class to be multicore parallelized. Please look at FPFHEstimationOMP for an example of a parallel implementation of the FPFH (Fast Point Feature Histogram).
Author
Radu B. Rusu
Definition at line 72 of file vfh.h.
Member Typedef Documentation
ConstPtr
template<typename PointInT , typename PointNT , typename PointOutT = pcl::VFHSignature308> using pcl::VFHEstimation< PointInT, PointNT, PointOutT >::ConstPtr = shared_ptr<const VFHEstimation<PointInT, PointNT, PointOutT> >
Definition at line 86 of file vfh.h.
PointCloudOut
template<typename PointInT , typename PointNT , typename PointOutT = pcl::VFHSignature308> using pcl::VFHEstimation< PointInT, PointNT, PointOutT >::PointCloudOut = typename Feature<PointInT, PointOutT>::PointCloudOut
Definition at line 84 of file vfh.h.
Ptr
template<typename PointInT , typename PointNT , typename PointOutT = pcl::VFHSignature308> using pcl::VFHEstimation< PointInT, PointNT, PointOutT >::Ptr = shared_ptr<VFHEstimation<PointInT, PointNT, PointOutT> >
Definition at line 85 of file vfh.h.
Constructor & Destructor Documentation
VFHEstimation()
template<typename PointInT , typename PointNT , typename PointOutT = pcl::VFHSignature308> pcl::VFHEstimation< PointInT, PointNT, PointOutT >::VFHEstimation () inline
Empty constructor.
Definition at line 90 of file vfh.h.
Member Function Documentation
compute()
template<typename PointInT , typename PointNT , typename PointOutT > void pcl::VFHEstimation< PointInT, PointNT, PointOutT >::compute (PointCloudOut & output)
Overloaded computed method from pcl::Feature.
Parameters
[out] output the resultant point cloud model dataset containing the estimated features
Definition at line 65 of file vfh.hpp.
References pcl::PointCloud< PointT >::clear(), pcl::PointCloud< PointT >::header, pcl::PointCloud< PointT >::height, pcl::PointCloud< PointT >::is_dense, pcl::PointCloud< PointT >::resize(), and pcl::PointCloud< PointT >::width.
computePointSPFHSignature()
template<typename PointInT , typename PointNT , typename PointOutT > void pcl::VFHEstimation< PointInT, PointNT, PointOutT >::computePointSPFHSignature (const Eigen::Vector4f & centroid_p, const Eigen::Vector4f & centroid_n, const pcl::PointCloud< PointInT > & cloud, const pcl::PointCloud< PointNT > & normals, const pcl::Indices & indices)
Estimate the SPFH (Simple Point Feature Histograms) signatures of the angular (f1, f2, f3) and distance (f4) features for a given point from its neighborhood.
Parameters
[in] centroid_p the centroid point
[in] centroid_n the centroid normal
[in] cloud the dataset containing the XYZ Cartesian coordinates of the two points
[in] normals the dataset containing the surface normals at each point in cloud
[in] indices the k-neighborhood point indices in the dataset
Definition at line 92 of file vfh.hpp.
References pcl::computePairFeatures(), pcl::getMaxDistance(), M_PI, and pcl_round().
getViewPoint()
template<typename PointInT , typename PointNT , typename PointOutT = pcl::VFHSignature308> void pcl::VFHEstimation< PointInT, PointNT, PointOutT >::getViewPoint (float & vpx, float & vpy, float & vpz) inline
Get the viewpoint.
Definition at line 134 of file vfh.h.
initCompute()
template<typename PointInT , typename PointNT , typename PointOutT > bool pcl::VFHEstimation< PointInT, PointNT, PointOutT >::initCompute override protected virtual
This method should get called before starting the actual computation.
Reimplemented from pcl::FeatureFromNormals< PointInT, PointNT, pcl::VFHSignature308 >.
Definition at line 51 of file vfh.hpp.
setCentroidToUse()
template<typename PointInT , typename PointNT , typename PointOutT = pcl::VFHSignature308> void pcl::VFHEstimation< PointInT, PointNT, PointOutT >::setCentroidToUse (const Eigen::Vector3f & centroid) inline
Set centroid_to_use_.
Parameters
[in] centroid Centroid to be used in the VFH computation. It is used to compute the distances from all points to this centroid.
Definition at line 174 of file vfh.h.
References pcl::VFHEstimation< PointInT, PointNT, PointOutT >::centroid_to_use_.
setFillSizeComponent()
template<typename PointInT , typename PointNT , typename PointOutT = pcl::VFHSignature308> void pcl::VFHEstimation< PointInT, PointNT, PointOutT >::setFillSizeComponent (bool fill_size) inline
set size_component_
Parameters
[in] fill_size True if the 4th component of VFH (shape distribution component) needs to be filled. Otherwise, it is set to zero.
Definition at line 203 of file vfh.h.
References pcl::VFHEstimation< PointInT, PointNT, PointOutT >::size_component_.
setNormalizeBins()
template<typename PointInT , typename PointNT , typename PointOutT = pcl::VFHSignature308> void pcl::VFHEstimation< PointInT, PointNT, PointOutT >::setNormalizeBins (bool normalize) inline
set normalize_bins_
Parameters
[in] normalize If true, the VFH bins are normalized using the total number of points
Definition at line 183 of file vfh.h.
References pcl::VFHEstimation< PointInT, PointNT, PointOutT >::normalize_bins_.
setNormalizeDistance()
template<typename PointInT , typename PointNT , typename PointOutT = pcl::VFHSignature308> void pcl::VFHEstimation< PointInT, PointNT, PointOutT >::setNormalizeDistance (bool normalize) inline
set normalize_distances_
Parameters
[in] normalize If true, the 4th component of VFH (shape distribution component) get normalized by the maximum size between the centroid and the point cloud
Definition at line 193 of file vfh.h.
References pcl::VFHEstimation< PointInT, PointNT, PointOutT >::normalize_distances_.
setNormalToUse()
template<typename PointInT , typename PointNT , typename PointOutT = pcl::VFHSignature308> void pcl::VFHEstimation< PointInT, PointNT, PointOutT >::setNormalToUse (const Eigen::Vector3f & normal) inline
Set the normal to use.
Parameters
[in] normal Sets the normal to be used in the VFH computation. It is is used to build the Darboux Coordinate system.
Definition at line 155 of file vfh.h.
References pcl::VFHEstimation< PointInT, PointNT, PointOutT >::normal_to_use_.
setUseGivenCentroid()
template<typename PointInT , typename PointNT , typename PointOutT = pcl::VFHSignature308> void pcl::VFHEstimation< PointInT, PointNT, PointOutT >::setUseGivenCentroid (bool use) inline
Set use_given_centroid_.
Parameters
[in] use Set to true if you want to use the centroid passed through setCentroidToUse(centroid)
Definition at line 164 of file vfh.h.
References pcl::VFHEstimation< PointInT, PointNT, PointOutT >::use_given_centroid_.
setUseGivenNormal()
template<typename PointInT , typename PointNT , typename PointOutT = pcl::VFHSignature308> void pcl::VFHEstimation< PointInT, PointNT, PointOutT >::setUseGivenNormal (bool use) inline
Set use_given_normal_.
Parameters
[in] use Set to true if you want to use the normal passed to setNormalUse(normal)
Definition at line 145 of file vfh.h.
References pcl::VFHEstimation< PointInT, PointNT, PointOutT >::use_given_normal_.
setViewPoint()
template<typename PointInT , typename PointNT , typename PointOutT = pcl::VFHSignature308> void pcl::VFHEstimation< PointInT, PointNT, PointOutT >::setViewPoint (float vpx, float vpy, float vpz) inline
Set the viewpoint.
Parameters
[in] vpx the X coordinate of the viewpoint
[in] vpy the Y coordinate of the viewpoint
[in] vpz the Z coordinate of the viewpoint
Definition at line 125 of file vfh.h.
Member Data Documentation
centroid_to_use_
template<typename PointInT , typename PointNT , typename PointOutT = pcl::VFHSignature308> Eigen::Vector4f pcl::VFHEstimation< PointInT, PointNT, PointOutT >::centroid_to_use_ protected
Centroid to be used to computed VFH.
Default, the centroid of the whole point cloud
Definition at line 246 of file vfh.h.
Referenced by pcl::VFHEstimation< PointInT, PointNT, PointOutT >::setCentroidToUse().
hist_f_
template<typename PointInT , typename PointNT , typename PointOutT = pcl::VFHSignature308> std::array<Eigen::VectorXf, 4> pcl::VFHEstimation< PointInT, PointNT, PointOutT >::hist_f_ protected
Placeholder for the f1 histogram.
Definition at line 239 of file vfh.h.
hist_vp_
template<typename PointInT , typename PointNT , typename PointOutT = pcl::VFHSignature308> Eigen::VectorXf pcl::VFHEstimation< PointInT, PointNT, PointOutT >::hist_vp_ protected
Placeholder for the vp histogram.
Definition at line 241 of file vfh.h.
normal_to_use_
template<typename PointInT , typename PointNT , typename PointOutT = pcl::VFHSignature308> Eigen::Vector4f pcl::VFHEstimation< PointInT, PointNT, PointOutT >::normal_to_use_ protected
Normal to be used to computed VFH.
Default, the average normal of the whole point cloud
Definition at line 244 of file vfh.h.
Referenced by pcl::VFHEstimation< PointInT, PointNT, PointOutT >::setNormalToUse().
normalize_bins_
template<typename PointInT , typename PointNT , typename PointOutT = pcl::VFHSignature308> bool pcl::VFHEstimation< PointInT, PointNT, PointOutT >::normalize_bins_ protected
Normalize bins by the number the total number of points.
Definition at line 255 of file vfh.h.
Referenced by pcl::VFHEstimation< PointInT, PointNT, PointOutT >::setNormalizeBins().
normalize_distances_
template<typename PointInT , typename PointNT , typename PointOutT = pcl::VFHSignature308> bool pcl::VFHEstimation< PointInT, PointNT, PointOutT >::normalize_distances_ protected
Normalize the shape distribution component of VFH.
Definition at line 257 of file vfh.h.
Referenced by pcl::VFHEstimation< PointInT, PointNT, PointOutT >::setNormalizeDistance().
size_component_
template<typename PointInT , typename PointNT , typename PointOutT = pcl::VFHSignature308> bool pcl::VFHEstimation< PointInT, PointNT, PointOutT >::size_component_ protected
Activate or deactivate the size component of VFH.
Definition at line 259 of file vfh.h.
Referenced by pcl::VFHEstimation< PointInT, PointNT, PointOutT >::setFillSizeComponent().
use_given_centroid_
template<typename PointInT , typename PointNT , typename PointOutT = pcl::VFHSignature308> bool pcl::VFHEstimation< PointInT, PointNT, PointOutT >::use_given_centroid_ protected
Use the centroid_to_use_.
Definition at line 253 of file vfh.h.
Referenced by pcl::VFHEstimation< PointInT, PointNT, PointOutT >::setUseGivenCentroid().
use_given_normal_
template<typename PointInT , typename PointNT , typename PointOutT = pcl::VFHSignature308> bool pcl::VFHEstimation< PointInT, PointNT, PointOutT >::use_given_normal_ protected
Use the normal_to_use_.
Definition at line 251 of file vfh.h.
Referenced by pcl::VFHEstimation< PointInT, PointNT, PointOutT >::setUseGivenNormal().
The documentation for this class was generated from the following files:
pcl/features/vfh.h
pcl/features/impl/vfh.hpp
© 20092012, Willow Garage, Inc.
© 2012, Open Perception, Inc.
Licensed under the BSD License.
https://pointclouds.org/documentation/classpcl_1_1_v_f_h_estimation.html