NormalEstimation estimates local surface properties (surface normals and curvatures)at each 3D point.
#include <pcl/features/normal_3d.h>
Public Types
using Ptr = shared_ptr< NormalEstimation< PointInT, PointOutT > >
using ConstPtr = shared_ptr< const NormalEstimation< PointInT, PointOutT > >
using PointCloudOut = typename Feature< PointInT, PointOutT >::PointCloudOut
using PointCloudConstPtr = typename Feature< PointInT, PointOutT >::PointCloudConstPtr
Public Types inherited from pcl::Feature< PointInT, PointOutT >
using BaseClass = PCLBase< PointInT >
using Ptr = shared_ptr< Feature< PointInT, PointOutT > >
using ConstPtr = shared_ptr< const Feature< PointInT, PointOutT > >
using KdTree = pcl::search::Search< PointInT >
using KdTreePtr = typename KdTree::Ptr
using PointCloudIn = pcl::PointCloud< PointInT >
using PointCloudInPtr = typename PointCloudIn::Ptr
using PointCloudInConstPtr = typename PointCloudIn::ConstPtr
using PointCloudOut = pcl::PointCloud< PointOutT >
using SearchMethod = std::function< int(std::size_t, double, pcl::Indices &, std::vector< float > &)>
using SearchMethodSurface = std::function< int(const PointCloudIn &cloud, std::size_t index, double, pcl::Indices &, std::vector< float > &)>
Public Types inherited from pcl::PCLBase< PointInT >
using PointCloud = pcl::PointCloud< PointInT >
using PointCloudPtr = typename PointCloud::Ptr
using PointCloudConstPtr = typename PointCloud::ConstPtr
using PointIndicesPtr = PointIndices::Ptr
using PointIndicesConstPtr = PointIndices::ConstPtr
Public Member Functions
NormalEstimation ()
Empty constructor.
~NormalEstimation () override=default
Empty destructor.
bool computePointNormal (const pcl::PointCloud< PointInT > &cloud, const pcl::Indices &indices, Eigen::Vector4f &plane_parameters, float &curvature)
Compute the Least-Squares plane fit for a given set of points, using their indices, and return the estimated plane parameters together with the surface curvature.
bool computePointNormal (const pcl::PointCloud< PointInT > &cloud, const pcl::Indices &indices, float &nx, float &ny, float &nz, float &curvature)
Compute the Least-Squares plane fit for a given set of points, using their indices, and return the estimated plane parameters together with the surface curvature.
void setInputCloud (const PointCloudConstPtr &cloud) override
Provide a pointer to the input dataset.
void setViewPoint (float vpx, float vpy, float vpz)
Set the viewpoint.
void getViewPoint (float &vpx, float &vpy, float &vpz)
Get the viewpoint.
void useSensorOriginAsViewPoint ()
sets whether the sensor origin or a user given viewpoint should be used.
Public Member Functions inherited from pcl::Feature< PointInT, PointOutT >
Feature ()
Empty constructor.
void setSearchSurface (const PointCloudInConstPtr &cloud)
Provide a pointer to a dataset to add additional information to estimate the features for every point in the input dataset.
PointCloudInConstPtr getSearchSurface () const
Get a pointer to the surface point cloud dataset.
void setSearchMethod (const KdTreePtr &tree)
Provide a pointer to the search object.
KdTreePtr getSearchMethod () const
Get a pointer to the search method used.
double getSearchParameter () const
Get the internal search parameter.
void setKSearch (int k)
Set the number of k nearest neighbors to use for the feature estimation.
int getKSearch () const
get the number of k nearest neighbors used for the feature estimation.
void setRadiusSearch (double radius)
Set the sphere radius that is to be used for determining the nearest neighbors used for the feature estimation.
double getRadiusSearch () const
Get the sphere radius used for determining the neighbors.
void compute (PointCloudOut &output)
Base method for feature estimation for all points given in <setInputCloud (), setIndices ()> using the surface in setSearchSurface () and the spatial locator in setSearchMethod ()
Public Member Functions inherited from pcl::PCLBase< PointInT >
PCLBase ()
Empty constructor.
PCLBase (const PCLBase &base)
Copy constructor.
virtual ~PCLBase ()=default
Destructor.
virtual void setInputCloud (const PointCloudConstPtr &cloud)
Provide a pointer to the input dataset.
PointCloudConstPtr const getInputCloud () const
Get a pointer to the input point cloud dataset.
virtual void setIndices (const IndicesPtr &indices)
Provide a pointer to the vector of indices that represents the input data.
virtual void setIndices (const IndicesConstPtr &indices)
Provide a pointer to the vector of indices that represents the input data.
virtual void setIndices (const PointIndicesConstPtr &indices)
Provide a pointer to the vector of indices that represents the input data.
virtual void setIndices (std::size_t row_start, std::size_t col_start, std::size_t nb_rows, std::size_t nb_cols)
Set the indices for the points laying within an interest region of the point cloud.
IndicesPtr getIndices ()
Get a pointer to the vector of indices used.
IndicesConstPtr const getIndices () const
Get a pointer to the vector of indices used.
const PointInT & operator[] (std::size_t pos) const
Override PointCloud operator[] to shorten code.
Protected Member Functions
void computeFeature (PointCloudOut &output) override
Estimate normals for all points given in <setInputCloud (), setIndices ()> using the surface in setSearchSurface () and the spatial locator in setSearchMethod ()
Protected Member Functions inherited from pcl::Feature< PointInT, PointOutT >
const std::string & getClassName () const
Get a string representation of the name of this class.
virtual bool initCompute ()
This method should get called before starting the actual computation.
virtual bool deinitCompute ()
This method should get called after ending the actual computation.
int searchForNeighbors (std::size_t index, double parameter, pcl::Indices &indices, std::vector< float > &distances) const
Search for k-nearest neighbors using the spatial locator from setSearchmethod, and the given surface from setSearchSurface.
int searchForNeighbors (const PointCloudIn &cloud, std::size_t index, double parameter, pcl::Indices &indices, std::vector< float > &distances) const
Search for k-nearest neighbors using the spatial locator from setSearchmethod, and the given surface from setSearchSurface.
Protected Member Functions inherited from pcl::PCLBase< PointInT >
bool initCompute ()
This method should get called before starting the actual computation.
bool deinitCompute ()
This method should get called after finishing the actual computation.
Protected Attributes
float vpx_
Values describing the viewpoint ("pinhole" camera model assumed).
float vpy_
float vpz_
EIGEN_ALIGN16 Eigen::Matrix3f covariance_matrix_
Placeholder for the 3x3 covariance matrix at each surface patch.
Eigen::Vector4f xyz_centroid_
16-bytes aligned placeholder for the XYZ centroid of a surface patch.
bool use_sensor_origin_
whether the sensor origin of the input cloud or a user given viewpoint should be used.
Protected Attributes inherited from pcl::Feature< PointInT, PointOutT >
std::string feature_name_
The feature name.
SearchMethodSurface search_method_surface_
The search method template for points.
PointCloudInConstPtr surface_
An input point cloud describing the surface that is to be used for nearest neighbors estimation.
KdTreePtr tree_
A pointer to the spatial search object.
double search_parameter_
The actual search parameter (from either search_radius_ or k_).
double search_radius_
The nearest neighbors search radius for each point.
int k_
The number of K nearest neighbors to use for each point.
bool fake_surface_
If no surface is given, we use the input PointCloud as the surface.
Protected Attributes inherited from pcl::PCLBase< PointInT >
PointCloudConstPtr input_
The input point cloud dataset.
IndicesPtr indices_
A pointer to the vector of point indices to use.
bool use_indices_
Set to true if point indices are used.
bool fake_indices_
If no set of indices are given, we construct a set of fake indices that mimic the input PointCloud.
Detailed Description
template<typename PointInT, typename PointOutT>
class pcl::NormalEstimation< PointInT, PointOutT >
NormalEstimation estimates local surface properties (surface normals and curvatures)at each 3D point.
If PointOutT is specified as pcl::Normal, the normal is stored in the first 3 components (0-2), and the curvature is stored in component 3.
Note
The code is stateful as we do not expect this class to be multicore parallelized. Please look at NormalEstimationOMP for a parallel implementation.
Author
Radu B. Rusu
Definition at line 243 of file normal_3d.h.
Member Typedef Documentation
ConstPtr
template<typename PointInT , typename PointOutT > using pcl::NormalEstimation< PointInT, PointOutT >::ConstPtr = shared_ptr<const NormalEstimation<PointInT, PointOutT> >
Definition at line 247 of file normal_3d.h.
PointCloudConstPtr
template<typename PointInT , typename PointOutT > using pcl::NormalEstimation< PointInT, PointOutT >::PointCloudConstPtr = typename Feature<PointInT, PointOutT>::PointCloudConstPtr
Definition at line 258 of file normal_3d.h.
PointCloudOut
template<typename PointInT , typename PointOutT > using pcl::NormalEstimation< PointInT, PointOutT >::PointCloudOut = typename Feature<PointInT, PointOutT>::PointCloudOut
Definition at line 257 of file normal_3d.h.
Ptr
template<typename PointInT , typename PointOutT > using pcl::NormalEstimation< PointInT, PointOutT >::Ptr = shared_ptr<NormalEstimation<PointInT, PointOutT> >
Definition at line 246 of file normal_3d.h.
Constructor & Destructor Documentation
NormalEstimation()
template<typename PointInT , typename PointOutT > pcl::NormalEstimation< PointInT, PointOutT >::NormalEstimation () inline
Empty constructor.
Definition at line 261 of file normal_3d.h.
References pcl::Feature< PointInT, PointOutT >::feature_name_.
~NormalEstimation()
template<typename PointInT , typename PointOutT > pcl::NormalEstimation< PointInT, PointOutT >::~NormalEstimation () override default
Empty destructor.
Member Function Documentation
computeFeature()
template<typename PointInT , typename PointOutT > void pcl::NormalEstimation< PointInT, PointOutT >::computeFeature (PointCloudOut & output) override protected virtual
Estimate normals for all points given in <setInputCloud (), setIndices ()> using the surface in setSearchSurface () and the spatial locator in setSearchMethod ()
Note
In situations where not enough neighbors are found, the normal and curvature values are set to NaN.
Parameters
output the resultant point cloud model dataset that contains surface normals and curvatures
Implements pcl::Feature< PointInT, PointOutT >.
Definition at line 48 of file normal_3d.hpp.
References pcl::computePointNormal(), pcl::flipNormalTowardsViewpoint(), pcl::PointCloud< PointT >::is_dense, and pcl::isFinite().
computePointNormal() [1/2]
template<typename PointInT , typename PointOutT > bool pcl::NormalEstimation< PointInT, PointOutT >::computePointNormal (const pcl::PointCloud< PointInT > & cloud, const pcl::Indices & indices, Eigen::Vector4f & plane_parameters, float & curvature) inline
Compute the Least-Squares plane fit for a given set of points, using their indices, and return the estimated plane parameters together with the surface curvature.
Parameters
cloud the input point cloud
indices the point cloud indices that need to be used
plane_parameters the plane parameters as: a, b, c, d (ax + by + cz + d = 0)
curvature the estimated surface curvature as a measure of
Definition at line 284 of file normal_3d.h.
References pcl::computeMeanAndCovarianceMatrix(), pcl::NormalEstimation< PointInT, PointOutT >::covariance_matrix_, pcl::solvePlaneParameters(), and pcl::NormalEstimation< PointInT, PointOutT >::xyz_centroid_.
computePointNormal() [2/2]
template<typename PointInT , typename PointOutT > bool pcl::NormalEstimation< PointInT, PointOutT >::computePointNormal (const pcl::PointCloud< PointInT > & cloud, const pcl::Indices & indices, float & nx, float & ny, float & nz, float & curvature) inline
Compute the Least-Squares plane fit for a given set of points, using their indices, and return the estimated plane parameters together with the surface curvature.
Parameters
cloud the input point cloud
indices the point cloud indices that need to be used
nx the resultant X component of the plane normal
ny the resultant Y component of the plane normal
nz the resultant Z component of the plane normal
curvature the estimated surface curvature as a measure of
Definition at line 313 of file normal_3d.h.
References pcl::computeMeanAndCovarianceMatrix(), pcl::NormalEstimation< PointInT, PointOutT >::covariance_matrix_, pcl::solvePlaneParameters(), and pcl::NormalEstimation< PointInT, PointOutT >::xyz_centroid_.
getViewPoint()
template<typename PointInT , typename PointOutT > void pcl::NormalEstimation< PointInT, PointOutT >::getViewPoint (float & vpx, float & vpy, float & vpz) inline
Get the viewpoint.
Parameters
[out] vpx x-coordinate of the view point
[out] vpy y-coordinate of the view point
[out] vpz z-coordinate of the view point
Note
this method returns the currently used viewpoint for normal flipping. If the viewpoint is set manually using the setViewPoint method, this method will return the set view point coordinates. If an input cloud is set, it will return the sensor origin otherwise it will return the origin (0, 0, 0)
Definition at line 366 of file normal_3d.h.
References pcl::NormalEstimation< PointInT, PointOutT >::vpx_, pcl::NormalEstimation< PointInT, PointOutT >::vpy_, and pcl::NormalEstimation< PointInT, PointOutT >::vpz_.
setInputCloud()
template<typename PointInT , typename PointOutT > void pcl::NormalEstimation< PointInT, PointOutT >::setInputCloud (const PointCloudConstPtr & cloud) inline override
Provide a pointer to the input dataset.
Parameters
cloud the const boost shared pointer to a PointCloud message
Definition at line 332 of file normal_3d.h.
References pcl::PCLBase< PointInT >::input_, pcl::NormalEstimation< PointInT, PointOutT >::use_sensor_origin_, pcl::NormalEstimation< PointInT, PointOutT >::vpx_, pcl::NormalEstimation< PointInT, PointOutT >::vpy_, and pcl::NormalEstimation< PointInT, PointOutT >::vpz_.
Referenced by pcl::UnaryClassifier< PointT >::computeFPFH(), pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::computeRf(), pcl::HarrisKeypoint6D< PointInT, PointOutT, NormalT >::detectKeypoints(), pcl::gpu::DataSource::estimateNormals(), pcl::HarrisKeypoint3D< PointInT, PointOutT, NormalT >::initCompute(), pcl::ISSKeypoint3D< PointInT, PointOutT, NormalT >::initCompute(), and pcl::SUSANKeypoint< PointInT, PointOutT, NormalT, IntensityT >::initCompute().
setViewPoint()
template<typename PointInT , typename PointOutT > void pcl::NormalEstimation< PointInT, PointOutT >::setViewPoint (float vpx, float vpy, float vpz) inline
Set the viewpoint.
Parameters
vpx the X coordinate of the viewpoint
vpy the Y coordinate of the viewpoint
vpz the Z coordinate of the viewpoint
Definition at line 349 of file normal_3d.h.
References pcl::NormalEstimation< PointInT, PointOutT >::use_sensor_origin_, pcl::NormalEstimation< PointInT, PointOutT >::vpx_, pcl::NormalEstimation< PointInT, PointOutT >::vpy_, and pcl::NormalEstimation< PointInT, PointOutT >::vpz_.
useSensorOriginAsViewPoint()
template<typename PointInT , typename PointOutT > void pcl::NormalEstimation< PointInT, PointOutT >::useSensorOriginAsViewPoint () inline
sets whether the sensor origin or a user given viewpoint should be used.
After this method, the normal estimation method uses the sensor origin of the input cloud. to use a user defined view point, use the method setViewPoint
Definition at line 378 of file normal_3d.h.
References pcl::PCLBase< PointInT >::input_, pcl::NormalEstimation< PointInT, PointOutT >::use_sensor_origin_, pcl::NormalEstimation< PointInT, PointOutT >::vpx_, pcl::NormalEstimation< PointInT, PointOutT >::vpy_, and pcl::NormalEstimation< PointInT, PointOutT >::vpz_.
Member Data Documentation
covariance_matrix_
template<typename PointInT , typename PointOutT > EIGEN_ALIGN16 Eigen::Matrix3f pcl::NormalEstimation< PointInT, PointOutT >::covariance_matrix_ protected
Placeholder for the 3x3 covariance matrix at each surface patch.
Definition at line 409 of file normal_3d.h.
Referenced by pcl::NormalEstimation< PointInT, PointOutT >::computePointNormal().
use_sensor_origin_
template<typename PointInT , typename PointOutT > bool pcl::NormalEstimation< PointInT, PointOutT >::use_sensor_origin_ protected
whether the sensor origin of the input cloud or a user given viewpoint should be used.
Definition at line 415 of file normal_3d.h.
Referenced by pcl::NormalEstimation< PointInT, PointOutT >::setInputCloud(), pcl::NormalEstimation< PointInT, PointOutT >::setViewPoint(), and pcl::NormalEstimation< PointInT, PointOutT >::useSensorOriginAsViewPoint().
vpx_
template<typename PointInT , typename PointOutT > float pcl::NormalEstimation< PointInT, PointOutT >::vpx_ protected
Values describing the viewpoint ("pinhole" camera model assumed).
For per point viewpoints, inherit from NormalEstimation and provide your own computeFeature (). By default, the viewpoint is set to 0,0,0.
Definition at line 406 of file normal_3d.h.
Referenced by pcl::NormalEstimation< PointInT, PointOutT >::getViewPoint(), pcl::NormalEstimation< PointInT, PointOutT >::setInputCloud(), pcl::NormalEstimation< PointInT, PointOutT >::setViewPoint(), and pcl::NormalEstimation< PointInT, PointOutT >::useSensorOriginAsViewPoint().
vpy_
template<typename PointInT , typename PointOutT > float pcl::NormalEstimation< PointInT, PointOutT >::vpy_ protected
Definition at line 406 of file normal_3d.h.
Referenced by pcl::NormalEstimation< PointInT, PointOutT >::getViewPoint(), pcl::NormalEstimation< PointInT, PointOutT >::setInputCloud(), pcl::NormalEstimation< PointInT, PointOutT >::setViewPoint(), and pcl::NormalEstimation< PointInT, PointOutT >::useSensorOriginAsViewPoint().
vpz_
template<typename PointInT , typename PointOutT > float pcl::NormalEstimation< PointInT, PointOutT >::vpz_ protected
Definition at line 406 of file normal_3d.h.
Referenced by pcl::NormalEstimation< PointInT, PointOutT >::getViewPoint(), pcl::NormalEstimation< PointInT, PointOutT >::setInputCloud(), pcl::NormalEstimation< PointInT, PointOutT >::setViewPoint(), and pcl::NormalEstimation< PointInT, PointOutT >::useSensorOriginAsViewPoint().
xyz_centroid_
template<typename PointInT , typename PointOutT > Eigen::Vector4f pcl::NormalEstimation< PointInT, PointOutT >::xyz_centroid_ protected
16-bytes aligned placeholder for the XYZ centroid of a surface patch.
Definition at line 412 of file normal_3d.h.
Referenced by pcl::NormalEstimation< PointInT, PointOutT >::computePointNormal().
The documentation for this class was generated from the following files:
pcl/features/normal_3d.h
pcl/features/impl/normal_3d.hpp
© 20092012, Willow Garage, Inc.
© 2012, Open Perception, Inc.
Licensed under the BSD License.
https://pointclouds.org/documentation/classpcl_1_1_normal_estimation.html