PrincipalCurvaturesEstimation estimates the directions (eigenvectors) and magnitudes (eigenvalues) of principal surface curvatures for a given point cloud dataset containing points and normals.
#include <pcl/features/principal_curvatures.h>
Public Types
using Ptr = shared_ptr< PrincipalCurvaturesEstimation< PointInT, PointNT, PointOutT > >
using ConstPtr = shared_ptr< const PrincipalCurvaturesEstimation< PointInT, PointNT, PointOutT > >
using PointCloudOut = typename Feature< PointInT, PointOutT >::PointCloudOut
using PointCloudIn = pcl::PointCloud< PointInT >
Public Types inherited from pcl::FeatureFromNormals< PointInT, PointNT, pcl::PrincipalCurvatures >
using PointCloudN = pcl::PointCloud< PointNT >
using PointCloudNPtr = typename PointCloudN::Ptr
using PointCloudNConstPtr = typename PointCloudN::ConstPtr
using Ptr = shared_ptr< FeatureFromNormals< PointInT, PointNT, pcl::PrincipalCurvatures > >
using ConstPtr = shared_ptr< const FeatureFromNormals< PointInT, PointNT, pcl::PrincipalCurvatures > >
Public Types inherited from pcl::Feature< PointInT, PointOutT >
using BaseClass = PCLBase< PointInT >
using Ptr = shared_ptr< Feature< PointInT, PointOutT > >
using ConstPtr = shared_ptr< const Feature< PointInT, PointOutT > >
using KdTree = pcl::search::Search< PointInT >
using KdTreePtr = typename KdTree::Ptr
using PointCloudIn = pcl::PointCloud< PointInT >
using PointCloudInPtr = typename PointCloudIn::Ptr
using PointCloudInConstPtr = typename PointCloudIn::ConstPtr
using PointCloudOut = pcl::PointCloud< PointOutT >
using SearchMethod = std::function< int(std::size_t, double, pcl::Indices &, std::vector< float > &)>
using SearchMethodSurface = std::function< int(const PointCloudIn &cloud, std::size_t index, double, pcl::Indices &, std::vector< float > &)>
Public Types inherited from pcl::PCLBase< PointInT >
using PointCloud = pcl::PointCloud< PointInT >
using PointCloudPtr = typename PointCloud::Ptr
using PointCloudConstPtr = typename PointCloud::ConstPtr
using PointIndicesPtr = PointIndices::Ptr
using PointIndicesConstPtr = PointIndices::ConstPtr
Public Member Functions
PrincipalCurvaturesEstimation ()
Empty constructor.
void computePointPrincipalCurvatures (const pcl::PointCloud< PointNT > &normals, int p_idx, const pcl::Indices &indices, float &pcx, float &pcy, float &pcz, float &pc1, float &pc2)
Perform Principal Components Analysis (PCA) on the point normals of a surface patch in the tangent plane of the given point normal, and return the principal curvature (eigenvector of the max eigenvalue), along with both the max (pc1) and min (pc2) eigenvalues.
Public Member Functions inherited from pcl::FeatureFromNormals< PointInT, PointNT, pcl::PrincipalCurvatures >
FeatureFromNormals ()
Empty constructor.
void setInputNormals (const PointCloudNConstPtr &normals)
Provide a pointer to the input dataset that contains the point normals of the XYZ dataset.
PointCloudNConstPtr getInputNormals () const
Get a pointer to the normals of the input XYZ point cloud dataset.
Public Member Functions inherited from pcl::Feature< PointInT, PointOutT >
Feature ()
Empty constructor.
void setSearchSurface (const PointCloudInConstPtr &cloud)
Provide a pointer to a dataset to add additional information to estimate the features for every point in the input dataset.
PointCloudInConstPtr getSearchSurface () const
Get a pointer to the surface point cloud dataset.
void setSearchMethod (const KdTreePtr &tree)
Provide a pointer to the search object.
KdTreePtr getSearchMethod () const
Get a pointer to the search method used.
double getSearchParameter () const
Get the internal search parameter.
void setKSearch (int k)
Set the number of k nearest neighbors to use for the feature estimation.
int getKSearch () const
get the number of k nearest neighbors used for the feature estimation.
void setRadiusSearch (double radius)
Set the sphere radius that is to be used for determining the nearest neighbors used for the feature estimation.
double getRadiusSearch () const
Get the sphere radius used for determining the neighbors.
void compute (PointCloudOut &output)
Base method for feature estimation for all points given in <setInputCloud (), setIndices ()> using the surface in setSearchSurface () and the spatial locator in setSearchMethod ()
Public Member Functions inherited from pcl::PCLBase< PointInT >
PCLBase ()
Empty constructor.
PCLBase (const PCLBase &base)
Copy constructor.
virtual ~PCLBase ()=default
Destructor.
virtual void setInputCloud (const PointCloudConstPtr &cloud)
Provide a pointer to the input dataset.
PointCloudConstPtr const getInputCloud () const
Get a pointer to the input point cloud dataset.
virtual void setIndices (const IndicesPtr &indices)
Provide a pointer to the vector of indices that represents the input data.
virtual void setIndices (const IndicesConstPtr &indices)
Provide a pointer to the vector of indices that represents the input data.
virtual void setIndices (const PointIndicesConstPtr &indices)
Provide a pointer to the vector of indices that represents the input data.
virtual void setIndices (std::size_t row_start, std::size_t col_start, std::size_t nb_rows, std::size_t nb_cols)
Set the indices for the points laying within an interest region of the point cloud.
IndicesPtr getIndices ()
Get a pointer to the vector of indices used.
IndicesConstPtr const getIndices () const
Get a pointer to the vector of indices used.
const PointInT & operator[] (std::size_t pos) const
Override PointCloud operator[] to shorten code.
Protected Member Functions
void computeFeature (PointCloudOut &output) override
Estimate the principal curvature (eigenvector of the max eigenvalue), along with both the max (pc1) and min (pc2) eigenvalues for all points given in <setInputCloud (), setIndices ()> using the surface in setSearchSurface () and the spatial locator in setSearchMethod ()
Protected Member Functions inherited from pcl::FeatureFromNormals< PointInT, PointNT, pcl::PrincipalCurvatures >
virtual bool initCompute ()
This method should get called before starting the actual computation.
Protected Member Functions inherited from pcl::Feature< PointInT, PointOutT >
const std::string & getClassName () const
Get a string representation of the name of this class.
virtual bool deinitCompute ()
This method should get called after ending the actual computation.
int searchForNeighbors (std::size_t index, double parameter, pcl::Indices &indices, std::vector< float > &distances) const
Search for k-nearest neighbors using the spatial locator from setSearchmethod, and the given surface from setSearchSurface.
int searchForNeighbors (const PointCloudIn &cloud, std::size_t index, double parameter, pcl::Indices &indices, std::vector< float > &distances) const
Search for k-nearest neighbors using the spatial locator from setSearchmethod, and the given surface from setSearchSurface.
Protected Member Functions inherited from pcl::PCLBase< PointInT >
bool initCompute ()
This method should get called before starting the actual computation.
bool deinitCompute ()
This method should get called after finishing the actual computation.
Additional Inherited Members
Protected Attributes inherited from pcl::FeatureFromNormals< PointInT, PointNT, pcl::PrincipalCurvatures >
PointCloudNConstPtr normals_
A pointer to the input dataset that contains the point normals of the XYZ dataset.
Protected Attributes inherited from pcl::Feature< PointInT, PointOutT >
std::string feature_name_
The feature name.
SearchMethodSurface search_method_surface_
The search method template for points.
PointCloudInConstPtr surface_
An input point cloud describing the surface that is to be used for nearest neighbors estimation.
KdTreePtr tree_
A pointer to the spatial search object.
double search_parameter_
The actual search parameter (from either search_radius_ or k_).
double search_radius_
The nearest neighbors search radius for each point.
int k_
The number of K nearest neighbors to use for each point.
bool fake_surface_
If no surface is given, we use the input PointCloud as the surface.
Protected Attributes inherited from pcl::PCLBase< PointInT >
PointCloudConstPtr input_
The input point cloud dataset.
IndicesPtr indices_
A pointer to the vector of point indices to use.
bool use_indices_
Set to true if point indices are used.
bool fake_indices_
If no set of indices are given, we construct a set of fake indices that mimic the input PointCloud.
Detailed Description
template<typename PointInT, typename PointNT, typename PointOutT = pcl::PrincipalCurvatures>
class pcl::PrincipalCurvaturesEstimation< PointInT, PointNT, PointOutT >
PrincipalCurvaturesEstimation estimates the directions (eigenvectors) and magnitudes (eigenvalues) of principal surface curvatures for a given point cloud dataset containing points and normals.
The recommended PointOutT is pcl::PrincipalCurvatures.
Note
The code is stateful as we do not expect this class to be multicore parallelized. Please look at NormalEstimationOMP for an example on how to extend this to parallel implementations.
Author
Radu B. Rusu, Jared Glover
Definition at line 59 of file principal_curvatures.h.
Member Typedef Documentation
ConstPtr
template<typename PointInT , typename PointNT , typename PointOutT = pcl::PrincipalCurvatures> using pcl::PrincipalCurvaturesEstimation< PointInT, PointNT, PointOutT >::ConstPtr = shared_ptr<const PrincipalCurvaturesEstimation<PointInT, PointNT, PointOutT> >
Definition at line 63 of file principal_curvatures.h.
PointCloudIn
template<typename PointInT , typename PointNT , typename PointOutT = pcl::PrincipalCurvatures> using pcl::PrincipalCurvaturesEstimation< PointInT, PointNT, PointOutT >::PointCloudIn = pcl::PointCloud<PointInT>
Definition at line 74 of file principal_curvatures.h.
PointCloudOut
template<typename PointInT , typename PointNT , typename PointOutT = pcl::PrincipalCurvatures> using pcl::PrincipalCurvaturesEstimation< PointInT, PointNT, PointOutT >::PointCloudOut = typename Feature<PointInT, PointOutT>::PointCloudOut
Definition at line 73 of file principal_curvatures.h.
Ptr
template<typename PointInT , typename PointNT , typename PointOutT = pcl::PrincipalCurvatures> using pcl::PrincipalCurvaturesEstimation< PointInT, PointNT, PointOutT >::Ptr = shared_ptr<PrincipalCurvaturesEstimation<PointInT, PointNT, PointOutT> >
Definition at line 62 of file principal_curvatures.h.
Constructor & Destructor Documentation
PrincipalCurvaturesEstimation()
template<typename PointInT , typename PointNT , typename PointOutT = pcl::PrincipalCurvatures> pcl::PrincipalCurvaturesEstimation< PointInT, PointNT, PointOutT >::PrincipalCurvaturesEstimation () inline
Empty constructor.
Definition at line 77 of file principal_curvatures.h.
References pcl::Feature< PointInT, PointOutT >::feature_name_.
Member Function Documentation
computeFeature()
template<typename PointInT , typename PointNT , typename PointOutT > void pcl::PrincipalCurvaturesEstimation< PointInT, PointNT, PointOutT >::computeFeature (PointCloudOut & output) override protected virtual
Estimate the principal curvature (eigenvector of the max eigenvalue), along with both the max (pc1) and min (pc2) eigenvalues for all points given in <setInputCloud (), setIndices ()> using the surface in setSearchSurface () and the spatial locator in setSearchMethod ()
Parameters
[out] output the resultant point cloud model dataset that contains the principal curvature estimates
Implements pcl::Feature< PointInT, PointOutT >.
Definition at line 115 of file principal_curvatures.hpp.
References pcl::PointCloud< PointT >::is_dense, and pcl::isFinite().
computePointPrincipalCurvatures()
template<typename PointInT , typename PointNT , typename PointOutT > void pcl::PrincipalCurvaturesEstimation< PointInT, PointNT, PointOutT >::computePointPrincipalCurvatures (const pcl::PointCloud< PointNT > & normals, int p_idx, const pcl::Indices & indices, float & pcx, float & pcy, float & pcz, float & pc1, float & pc2)
Perform Principal Components Analysis (PCA) on the point normals of a surface patch in the tangent plane of the given point normal, and return the principal curvature (eigenvector of the max eigenvalue), along with both the max (pc1) and min (pc2) eigenvalues.
Parameters
[in] normals the point cloud normals
[in] p_idx the query point at which the least-squares plane was estimated
[in] indices the point cloud indices that need to be used
[out] pcx the principal curvature X direction
[out] pcy the principal curvature Y direction
[out] pcz the principal curvature Z direction
[out] pc1 the max eigenvalue of curvature
[out] pc2 the min eigenvalue of curvature
Definition at line 50 of file principal_curvatures.hpp.
References pcl::computeCorrespondingEigenVector(), and pcl::eigen33().
The documentation for this class was generated from the following files:
pcl/features/principal_curvatures.h
pcl/features/impl/principal_curvatures.hpp
© 20092012, Willow Garage, Inc.
© 2012, Open Perception, Inc.
Licensed under the BSD License.
https://pointclouds.org/documentation/classpcl_1_1_principal_curvatures_estimation.html