ConditionalRemoval filters data that satisfies certain conditions.
#include <pcl/filters/conditional_removal.h>
Public Types
using ConditionBase = pcl::ConditionBase< PointT >
using ConditionBasePtr = typename ConditionBase::Ptr
using ConditionBaseConstPtr = typename ConditionBase::ConstPtr
using Ptr = shared_ptr< ConditionalRemoval< PointT > >
using ConstPtr = shared_ptr< const ConditionalRemoval< PointT > >
Public Types inherited from pcl::Filter< PointT >
using Ptr = shared_ptr< Filter< PointT > >
using ConstPtr = shared_ptr< const Filter< PointT > >
using PointCloud = pcl::PointCloud< PointT >
using PointCloudPtr = typename PointCloud::Ptr
using PointCloudConstPtr = typename PointCloud::ConstPtr
Public Types inherited from pcl::PCLBase< PointT >
using PointCloud = pcl::PointCloud< PointT >
using PointCloudPtr = typename PointCloud::Ptr
using PointCloudConstPtr = typename PointCloud::ConstPtr
using PointIndicesPtr = PointIndices::Ptr
using PointIndicesConstPtr = PointIndices::ConstPtr
Public Member Functions
ConditionalRemoval (int extract_removed_indices=false)
the default constructor.
void setKeepOrganized (bool val)
Set whether the filtered points should be kept and set to the value given through setUserFilterValue (default: NaN), or removed from the PointCloud, thus potentially breaking its organized structure.
bool getKeepOrganized () const
void setUserFilterValue (float val)
Provide a value that the filtered points should be set to instead of removing them.
void setCondition (ConditionBasePtr condition)
Set the condition that the filter will use.
Public Member Functions inherited from pcl::Filter< PointT >
Filter (bool extract_removed_indices=false)
Empty constructor.
IndicesConstPtr const getRemovedIndices () const
Get the point indices being removed.
void getRemovedIndices (PointIndices &pi)
Get the point indices being removed.
void filter (PointCloud &output)
Calls the filtering method and returns the filtered dataset in output.
Public Member Functions inherited from pcl::PCLBase< PointT >
PCLBase ()
Empty constructor.
PCLBase (const PCLBase &base)
Copy constructor.
virtual ~PCLBase ()=default
Destructor.
virtual void setInputCloud (const PointCloudConstPtr &cloud)
Provide a pointer to the input dataset.
PointCloudConstPtr const getInputCloud () const
Get a pointer to the input point cloud dataset.
virtual void setIndices (const IndicesPtr &indices)
Provide a pointer to the vector of indices that represents the input data.
virtual void setIndices (const IndicesConstPtr &indices)
Provide a pointer to the vector of indices that represents the input data.
virtual void setIndices (const PointIndicesConstPtr &indices)
Provide a pointer to the vector of indices that represents the input data.
virtual void setIndices (std::size_t row_start, std::size_t col_start, std::size_t nb_rows, std::size_t nb_cols)
Set the indices for the points laying within an interest region of the point cloud.
IndicesPtr getIndices ()
Get a pointer to the vector of indices used.
IndicesConstPtr const getIndices () const
Get a pointer to the vector of indices used.
const PointT & operator[] (std::size_t pos) const
Override PointCloud operator[] to shorten code.
Protected Member Functions
void applyFilter (PointCloud &output) override
Filter a Point Cloud.
Protected Member Functions inherited from pcl::Filter< PointT >
const std::string & getClassName () const
Get a string representation of the name of this class.
Protected Member Functions inherited from pcl::PCLBase< PointT >
bool initCompute ()
This method should get called before starting the actual computation.
bool deinitCompute ()
This method should get called after finishing the actual computation.
Protected Attributes
bool capable_
True if capable.
bool keep_organized_
Keep the structure of the data organized, by setting the filtered points to the a user given value (NaN by default).
ConditionBasePtr condition_
The condition to use for filtering.
float user_filter_value_
User given value to be set to any filtered point.
Protected Attributes inherited from pcl::Filter< PointT >
IndicesPtr removed_indices_
Indices of the points that are removed.
std::string filter_name_
The filter name.
bool extract_removed_indices_
Set to true if we want to return the indices of the removed points.
Protected Attributes inherited from pcl::PCLBase< PointT >
PointCloudConstPtr input_
The input point cloud dataset.
IndicesPtr indices_
A pointer to the vector of point indices to use.
bool use_indices_
Set to true if point indices are used.
bool fake_indices_
If no set of indices are given, we construct a set of fake indices that mimic the input PointCloud.
Detailed Description
template<typename PointT>
class pcl::ConditionalRemoval< PointT >
ConditionalRemoval filters data that satisfies certain conditions.
A ConditionalRemoval must be provided a condition. There are two types of conditions: ConditionAnd and ConditionOr. Conditions require one or more comparisons and/or other conditions. A comparison has a name, a comparison operator, and a value.
An ConditionAnd will evaluate to true when ALL of its encapsulated comparisons and conditions are true.
An ConditionOr will evaluate to true when ANY of its encapsulated comparisons and conditions are true.
Depending on the derived type of the comparison, the name can correspond to a PointCloud field name, or a color component in rgb color space or hsi color space.
Here is an example usage:
// Build the condition
pcl::ConditionAnd<PointT>::Ptr range_cond (new pcl::ConditionAnd<PointT> ());
range_cond->addComparison (pcl::FieldComparison<PointT>::Ptr (new pcl::FieldComparison<PointT>("z", pcl::ComparisonOps::LT, 2.0)));
range_cond->addComparison (pcl::FieldComparison<PointT>::Ptr (new pcl::FieldComparison<PointT>("z", pcl::ComparisonOps::GT, 0.0)));
// Build the filter
pcl::ConditionalRemoval<PointT> range_filt;
range_filt.setCondition (range_cond);
range_filt.setKeepOrganized (false);
pcl::ConditionAndAND condition.Definition: conditional_removal.h:505
pcl::ConditionAnd
AND condition.
Definition: conditional_removal.h:505
pcl::ConditionAnd::Ptrshared_ptr< ConditionAnd< PointT > > PtrDefinition: conditional_removal.h:510
pcl::ConditionAnd::Ptr
shared_ptr< ConditionAnd< PointT > > Ptr
Definition: conditional_removal.h:510
pcl::ConditionalRemovalConditionalRemoval filters data that satisfies certain conditions.Definition: conditional_removal.h:592
pcl::ConditionalRemoval
ConditionalRemoval filters data that satisfies certain conditions.
Definition: conditional_removal.h:592
pcl::ConditionalRemoval::setConditionvoid setCondition(ConditionBasePtr condition)Set the condition that the filter will use.Definition: conditional_removal.hpp:617
pcl::ConditionalRemoval::setCondition
void setCondition(ConditionBasePtr condition)
Set the condition that the filter will use.
Definition: conditional_removal.hpp:617
pcl::ConditionalRemoval::setKeepOrganizedvoid setKeepOrganized(bool val)Set whether the filtered points should be kept and set to the value given through setUserFilterValue ...Definition: conditional_removal.h:635
pcl::ConditionalRemoval::setKeepOrganized
void setKeepOrganized(bool val)
Set whether the filtered points should be kept and set to the value given through setUserFilterValue ...
Definition: conditional_removal.h:635
pcl::FieldComparisonThe field-based specialization of the comparison object.Definition: conditional_removal.h:130
pcl::FieldComparison
The field-based specialization of the comparison object.
Definition: conditional_removal.h:130
pcl::FieldComparison::Ptrshared_ptr< FieldComparison< PointT > > PtrDefinition: conditional_removal.h:136
pcl::FieldComparison::Ptr
shared_ptr< FieldComparison< PointT > > Ptr
Definition: conditional_removal.h:136
pcl::ComparisonOps::GT@ GTDefinition: conditional_removal.h:54
pcl::ComparisonOps::GT
@ GT
Definition: conditional_removal.h:54
pcl::ComparisonOps::LT@ LTDefinition: conditional_removal.h:54
pcl::ComparisonOps::LT
@ LT
Definition: conditional_removal.h:54
Author
Louis LeGrand, Intel Labs Seattle
Definition at line 591 of file conditional_removal.h.
Member Typedef Documentation
ConditionBase
template<typename PointT > using pcl::ConditionalRemoval< PointT >::ConditionBase = pcl::ConditionBase<PointT>
Definition at line 605 of file conditional_removal.h.
ConditionBaseConstPtr
template<typename PointT > using pcl::ConditionalRemoval< PointT >::ConditionBaseConstPtr = typename ConditionBase::ConstPtr
Definition at line 607 of file conditional_removal.h.
ConditionBasePtr
template<typename PointT > using pcl::ConditionalRemoval< PointT >::ConditionBasePtr = typename ConditionBase::Ptr
Definition at line 606 of file conditional_removal.h.
ConstPtr
template<typename PointT > using pcl::ConditionalRemoval< PointT >::ConstPtr = shared_ptr<const ConditionalRemoval<PointT> >
Definition at line 610 of file conditional_removal.h.
Ptr
template<typename PointT > using pcl::ConditionalRemoval< PointT >::Ptr = shared_ptr<ConditionalRemoval<PointT> >
Definition at line 609 of file conditional_removal.h.
Constructor & Destructor Documentation
ConditionalRemoval()
template<typename PointT > pcl::ConditionalRemoval< PointT >::ConditionalRemoval (int extract_removed_indices = false) inline
the default constructor.
All ConditionalRemovals require a condition which can be set using the setCondition method
Parameters
extract_removed_indices extract filtered indices from indices vector
Definition at line 619 of file conditional_removal.h.
References pcl::Filter< PointT >::filter_name_.
Member Function Documentation
applyFilter()
template<typename PointT > void pcl::ConditionalRemoval< PointT >::applyFilter (PointCloud & output) override protected virtual
Filter a Point Cloud.
Parameters
output the resultant point cloud message
Implements pcl::Filter< PointT >.
Definition at line 625 of file conditional_removal.hpp.
References pcl::copyPoint(), pcl::PointCloud< PointT >::header, pcl::PointCloud< PointT >::height, pcl::PointCloud< PointT >::is_dense, pcl::PointCloud< PointT >::resize(), and pcl::PointCloud< PointT >::width.
getKeepOrganized()
template<typename PointT > bool pcl::ConditionalRemoval< PointT >::getKeepOrganized () const inline
Definition at line 641 of file conditional_removal.h.
References pcl::ConditionalRemoval< PointT >::keep_organized_.
setCondition()
template<typename PointT > void pcl::ConditionalRemoval< PointT >::setCondition (ConditionBasePtr condition)
Set the condition that the filter will use.
Parameters
condition each point must satisfy this condition to avoid being removed by the filter
All ConditionalRemovals require a condition
Definition at line 617 of file conditional_removal.hpp.
Referenced by pcl::kinfuLS::WorldModel< PointT >::getExistingData(), and pcl::kinfuLS::WorldModel< PointT >::setSliceAsNans().
setKeepOrganized()
template<typename PointT > void pcl::ConditionalRemoval< PointT >::setKeepOrganized (bool val) inline
Set whether the filtered points should be kept and set to the value given through setUserFilterValue (default: NaN), or removed from the PointCloud, thus potentially breaking its organized structure.
By default, points are removed.
Parameters
val set to true whether the filtered points should be kept and set to a given user value (default: NaN)
Definition at line 635 of file conditional_removal.h.
References pcl::ConditionalRemoval< PointT >::keep_organized_.
Referenced by pcl::kinfuLS::WorldModel< PointT >::getExistingData(), and pcl::kinfuLS::WorldModel< PointT >::setSliceAsNans().
setUserFilterValue()
template<typename PointT > void pcl::ConditionalRemoval< PointT >::setUserFilterValue (float val) inline
Provide a value that the filtered points should be set to instead of removing them.
Used in conjunction with setKeepOrganized ().
Parameters
val the user given value that the filtered point dimensions should be set to
Definition at line 652 of file conditional_removal.h.
References pcl::ConditionalRemoval< PointT >::user_filter_value_.
Member Data Documentation
capable_
template<typename PointT > bool pcl::ConditionalRemoval< PointT >::capable_ protected
True if capable.
Definition at line 674 of file conditional_removal.h.
condition_
template<typename PointT > ConditionBasePtr pcl::ConditionalRemoval< PointT >::condition_ protected
The condition to use for filtering.
Definition at line 682 of file conditional_removal.h.
keep_organized_
template<typename PointT > bool pcl::ConditionalRemoval< PointT >::keep_organized_ protected
Keep the structure of the data organized, by setting the filtered points to the a user given value (NaN by default).
Definition at line 679 of file conditional_removal.h.
Referenced by pcl::ConditionalRemoval< PointT >::getKeepOrganized(), and pcl::ConditionalRemoval< PointT >::setKeepOrganized().
user_filter_value_
template<typename PointT > float pcl::ConditionalRemoval< PointT >::user_filter_value_ protected
User given value to be set to any filtered point.
Casted to the correct field type.
Definition at line 687 of file conditional_removal.h.
Referenced by pcl::ConditionalRemoval< PointT >::setUserFilterValue().
The documentation for this class was generated from the following files:
pcl/filters/conditional_removal.h
pcl/filters/impl/conditional_removal.hpp
© 20092012, Willow Garage, Inc.
© 2012, Open Perception, Inc.
Licensed under the BSD License.
https://pointclouds.org/documentation/classpcl_1_1_conditional_removal.html