name: Build Debian packages

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-debian-stable:
    runs-on: ubuntu-latest
    container: debian:stable

    steps:
      - run: |
          apt-get -y update
          apt-get -y upgrade
          apt-get -y install build-essential git

      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - run: |
          apt-get -y build-dep .
          dpkg-buildpackage --build=binary --no-sign

      - uses: svenstaro/upload-release-action@v2
        with:
          file_glob: true
          file: ../*.deb
          overwrite: true
