name: Debian Release

on:
  push:
    tags:
      - 'debian/*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6

      - env:
          FULL_NAME: ${{ github.repository }}
          FULL_TAG: ${{ github.ref_name }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          NAME="${FULL_NAME#*/}"
          VERS="${FULL_TAG#debian/}"
          VERS="${VERS#*[0-9]%}"

          gh release create "$FULL_TAG" --title "$NAME $VERS" --generate-notes
